### ISSUE TITLE
渗透服务不可用

### ISSUE THREAD

**Issue by ruixuedongyang** [FunnyWolf/Viper#1]
服务器上部署以后，msf模块无法启动，查看docker内的log显示检查60005端口，检查后发现端口并未占用
![msf](https://user-images.githubusercontent.com/29765332/103621171-c03b2d80-4f6f-11eb-8745-044050368943.png)
![端口](https://user-images.githubusercontent.com/29765332/103621175-c29d8780-4f6f-11eb-927a-3208854117ab.png)

**Comment by FunnyWolf** [comment]
> 服务器上部署以后，msf模块无法启动，查看docker内的log显示检查60005端口，检查后发现端口并未占用
> ![msf](https://user-images.githubusercontent.com/29765332/103621171-c03b2d80-4f6f-11eb-8745-044050368943.png)
> ![端口](https://user-images.githubusercontent.com/29765332/103621175-c29d8780-4f6f-11eb-927a-3208854117ab.png)

msf服务没起来，docker内部执行viper start

**Comment by swrite** [comment]
并没有55个模块，发现应该阉割掉了

**Comment by FunnyWolf** [comment]
> 并没有55个模块，发现应该阉割掉了

哈哈，没有阉割这种操作，生成一个session后再执行就会发现所有模块了，因为有些模块需要session,隐藏了

**Comment by ruixuedongyang** [comment]
内存太小了，起不起来。。。。。
换了个大内存的就好了
