### ISSUE TITLE
监听载荷部分有点疑问

### ISSUE THREAD

**Issue by ViCrack** [FunnyWolf/Viper#10]
![image](https://user-images.githubusercontent.com/18179821/109971871-a7fa4b80-7d31-11eb-9d3b-09a325e722cd.png)
点击虚拟化之后会重复多一条记录出来, 要取消监听的话 只能是删除当前监听的这个,  这块功能是设计如此么?

点击详情, 查看参数现在还无法支持编辑, 有时候填错了比较麻烦

![image](https://user-images.githubusercontent.com/18179821/109975133-450ab380-7d35-11eb-915a-1c514992157b.png)
linux 环境下console执行命令会报

/bin/sh: line 1: $'\r': command not found

**Comment by FunnyWolf** [comment]
虚拟化的功能是使用实际监听的配置新建一个虚拟监听,实例化是使用虚拟监听的配置新建一个真正的监听,可能是虚拟化这个名称容易让人误解将实际监听`转化`为虚拟监听

**Comment by FunnyWolf** [comment]
关于修改监听参数的功能,如果修改真实监听参数,可能会出现现有的Session掉线问题,不熟悉的人会很疑惑.
修改虚拟监听参数,暂时也想不到有哪些场景需要这个功能.
后续调研一下MSF如何动态的修改handler参数,已经将该需求放入到project中

**Comment by FunnyWolf** [comment]
linux无法执行shell命令已复现,暂时可以通过在meterpreter 执行 shell -c whoami 规避这个问题

**Comment by ViCrack** [comment]
点击虚拟化时确实会把当前实际监听的复制后新建一个新的虚拟监听, 但是点击实例化的时候只是把当前的转化为实际监听, 并没有新建一个, 所以我本以为是用来转化的功能

其实虚拟监听的我是事先建好主要用来方便生成载荷的, 不用每次都点一遍

**Comment by FunnyWolf** [comment]
> 点击虚拟化时确实会把当前实际监听的复制后新建一个新的虚拟监听, 但是点击实例化的时候只是把当前的转化为实际监听, 并没有新建一个, 所以我本以为是用来转化的功能
> 
> 其实虚拟监听的我是事先建好主要用来方便生成载荷的, 不用每次都点一遍

点击实例化时不会将对应的虚拟监听删除,在实际使用过程中点击实例化后原来的虚拟监听消失了吗?如果消失了可能是bug,预期不是这样.

**Comment by ViCrack** [comment]
再确认了一下现在又正常了, 之前可能是做了什么操作,  好像弹了几次新建监听超时之后才有的现象
