### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ma3h1r0** [FunnyWolf/Viper#101]
**描述Bug**
Request error 502: https://ip:60000/api/v1/core/currentuser/
Gateway error.

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 进入vpsip:60000 没有出现登录界面，直接进入了控制台，并且报错。

**截图**
请提供Bug出现时的截图.
![image](https://user-images.githubusercontent.com/76898760/183224877-dee17cf8-1323-498a-b115-33979349bd4d.png)

@Funnywolf

**Comment by Ma3h1r0** [comment]
补充一下，如果关闭ssl的话可以正常进入登录界面并登录 但是控制台会一直转圈圈

**Comment by FunnyWolf** [comment]
看一下是不是开浏览器代理了

**Comment by Ma3h1r0** [comment]
没有开e

**Comment by FunnyWolf** [comment]
无法复现,暂时关闭
