### ISSUE TITLE
viper无法暴力破解并且容易崩溃

### ISSUE THREAD

**Issue by zftishack** [FunnyWolf/Viper#105]
你好,我在使用过程中发现viper中的msf无法加载字典,还有一个问题就是当我传frp时候,viper很容易奔溃,我应该如何解决这两个问题了??

**Comment by zftishack** [comment]
就是爆破功能似乎根本用不了

**Comment by FunnyWolf** [comment]
> 

崩溃是指session掉了吗?

**Comment by FunnyWolf** [comment]
暴力破解用的是哪个模块?

**Comment by zftishack** [comment]
> 暴力破解用的是哪个模块?

我是使用f8x工具安装的viper，我之前试过好像无法加载字典，崩溃一般就是：访问页面能进去，但是啥都做不了啦，还有使用frp流量转发的过程中session也掉的特别快

**Comment by FunnyWolf** [comment]
> 

是最新版本吗?最近的一个版本刚解决msf卡死问题

**Comment by zftishack** [comment]
>好的谢谢
