### ISSUE TITLE
[BUG] 新安装完成后，默认的会话无法删除

### ISSUE THREAD

**Issue by woOzZ2** [FunnyWolf/Viper#109]
**描述Bug**
请简短描述遇到的Bug.
默认的会话无法删除

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 删除255.255.255.255主机
4. Bug出现了

**截图**
<img width="913" alt="image" src="https://user-images.githubusercontent.com/21095700/184868585-97866cca-0faf-452d-97fe-80c7447d4fd0.png">

@Funnywolf

**Comment by FunnyWolf** [comment]
特意这么设计的，为了在没有session时调用不需要session的模块
