### ISSUE TITLE
反馈几个问题。

### ISSUE THREAD

**Issue by SkyBlueEternal** [FunnyWolf/Viper#11]
LINUX 分离免杀载荷在KALI下面执行出现异常，ELF原生载荷也是会异常。

**Comment by SkyBlueEternal** [comment]
首先配置监听器之后，点击生成载荷会出现无法下载载荷的情况，云主机和虚拟机都测试过。

**Comment by FunnyWolf** [comment]
> 首先配置监听器之后，点击生成载荷会出现无法下载载荷的情况，云主机和虚拟机都测试过。

此问题无法复现

**Comment by FunnyWolf** [comment]
先关闭,后续复现再开启
