### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 80laotou** [FunnyWolf/Viper#110]
**作者你好，
我在树莓派上面搭建时，dockers里面并未启动系统，dockers日志提示信息是standard_init_linux.go:219: exec user process caused: exec format error。
 请问下作者是否对该处理器有过编译的版本’Linux debian 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux”

收到请回复，感谢作者的无私奉献。
@Funnywolf

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/106
