### ISSUE TITLE
关于ruby进程 CPU占用过高导致的渗透服务异常 临时解决方法

### ISSUE THREAD

**Issue by dayuwl** [FunnyWolf/Viper#112]
近期遇到了ruby进程占用CPU资源过高导致渗透服务异常的问题 研究了一下 找到了一个临时解决的方法：
有这种问题的 可以使用cpulimit限制ruby占用CPU阈值
1、安装cpulimit
sudo yum install epel-release cpulimit
2、使用ps -A找出pid
3、运行cpulimit --pid 进程pid --limit 50
执行之后，该进程的 CPU 用量就会被控制在 50% 左右
@Funnywolf

**Comment by FunnyWolf** [comment]
> 
cpu 100%重来没有复现过,50%以后服务是否可用?

**Comment by dayuwl** [comment]
我使用的是腾讯的轻量云服务器 CPU经常出现100% 我限制的是40% 可以正常使用

**Comment by dayuwl** [comment]
我使用的是腾讯的轻量云服务器 CPU经常出现100% 我限制的是40% 可以正常使用
@FunnyWolf

**Comment by FunnyWolf** [comment]
> 我使用的是腾讯的轻量云服务器 CPU经常出现100% 我限制的是40% 可以正常使用 @FunnyWolf

非常感谢，我会测试一下并更新文档

**Comment by dayuwl** [comment]
我还发现了一个问题 因为我用的是轻量 ruby这个进程CPU用量增加之后msf就连接失败
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!

**Comment by FunnyWolf** [comment]
> 我还发现了一个问题 因为我用的是轻量 ruby这个进程CPU用量增加之后msf就连接失败 msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用 json_rpc服务无法连接,请确认! msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用 json_rpc服务无法连接,请确认! msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用 json_rpc服务无法连接,请确认!

ruby就是msf进程

**Comment by dayuwl** [comment]
重启之后又回到正常的状态了 隔天又出现了  这个是服务器的问题吗 用轻量服务器太小了 需要换一个配置高的吗

**Comment by FunnyWolf** [comment]
> 

不是,是msf代码问题

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/759e9606754a365670ff587f991e47298c31a6a2
