### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by laughlove** [FunnyWolf/Viper#115]
关于viper的拓扑功能,是否可以新增取消或显示拓扑的功能,因为在用viper进行内网扫描时,可能会一次性出现非常多的主机,看起来会比较杂乱

**Comment by FunnyWolf** [comment]
> 

我理解是新增一个开关,可以打开/关闭显示没有session的主机的功能,这样拓扑就只显示有session的主机,是这样吧?

**Comment by FunnyWolf** [comment]
@laughlove

**Comment by laughlove** [comment]
是的，这样看着就不杂乱了

**Comment by FunnyWolf** [comment]
https://www.yuque.com/vipersec/help/vt9iyh
