### ISSUE TITLE
[BUG] 渗透服务异常

### ISSUE THREAD

**Issue by telegramerror** [FunnyWolf/Viper#119]
viperpython.log
json_rpc服务无法连接,请确认!
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!
内置模块加载完成,加载99个模块
自定义模块加载完成,加载0个模块
后台服务启动成功
Unauthorized: /api/v1/core/currentuser/
Unauthorized: /api/v1/core/currentuser/
Unauthorized: /api/v1/core/currentuser/
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
json_rpc服务无法连接,请确认!

**Comment by telegramerror** [comment]
无法重启渗透服务 Session全部超时

**Comment by telegramerror** [comment]
老哥还在维护吗，这个能解决的话就非常方便了

**Comment by netstatnao** [comment]
新版本是不是都有这个问，我也出现了这个问题，大佬什么时候能出山修复一下

**Comment by lml20000827** [comment]
docker进去后执行 service puma restart解决

**Comment by FunnyWolf** [comment]
汇总到以下issus,关闭此issus
https://github.com/FunnyWolf/Viper/issues/129

**Comment by Aliak15** [comment]
> 老哥还在维护吗，这个能解决的话就非常方便了

我运行了一条命令解决了，
docker-compose start
