### ISSUE TITLE
[BUG]密码修改失败

### ISSUE THREAD

**Issue by Ludovicofu** [FunnyWolf/Viper#120]
**描述Bug**
请简短描述遇到的Bug.
密码修改失败
**如何复现**
请说明如何复现Bug:
按照https://www.yuque.com/vipersec/help/rxb752，持久化修改密码
![image](https://user-images.githubusercontent.com/91811209/215060382-0f272526-306a-4c60-a33c-fff30da67b5a.png)
结果密码依然没有修改，有人和我一样的情况
![image](https://user-images.githubusercontent.com/91811209/215060484-79d09a94-31b8-473d-8f25-6e6dda7657e9.png)

**截图**
请提供Bug出现时的截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
文档已更新
https://www.yuque.com/vipersec/help/rxb752
