### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LiuYanJan** [FunnyWolf/Viper#121]
**描述Bug**
 netbios 扫描的结果都出现在 主机界面上面 ，而且没发现有批量删除的功能！！！

**如何复现**
使用netbios 扫描
**截图**
![image](https://user-images.githubusercontent.com/46078482/216225942-9f68b195-b989-4e51-8ade-03377def4dc6.png)

@Funnywolf

**Comment by LiuYanJan** [comment]
好叭 没看到有个 multi  以为融合在一起了， 没问题了

**Comment by FunnyWolf** [comment]
“netbios 扫描的结果都出现在 主机界面上面”
这个是符合预期的，便于内网渗透知道有哪些主机

“而且没发现有批量删除的功能！！！”

在《内网代理》标签下面有批量删除功能
