### ISSUE TITLE
不能生成Android 载荷，可不可以在msf6中生成载荷 然后在viper中使用？

### ISSUE THREAD

**Issue by liboy119** [FunnyWolf/Viper#126]

**Comment by FunnyWolf** [comment]
可以的,viper上添加对应的监听就可以.

**Comment by liboy119** [comment]
嗯嗯 谢谢回答 我们也没有类似的群交流 自己一个人研究太慢了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月18日(周二) 上午8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FunnyWolf/Viper] 不能生成Android 载荷，可不可以在msf6中生成载荷 然后在viper中使用？ (Issue #126)




 
可以的,viper上添加对应的监听就可以.
