### ISSUE TITLE
[BUG] 渗透服务连接失败,请检查MSFRPC状态 问题汇总

### ISSUE THREAD

**Issue by FunnyWolf** [FunnyWolf/Viper#129]
**描述Bug**
VIPER在运行一段时间之后会报错 "渗透服务连接失败,请检查MSFRPC状态".

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 创建一个reverse_tcp类型监听
3. 过一段时间之后
4. bug出现

**截图**
请提供Bug出现时的截图.
![image](https://user-images.githubusercontent.com/17685281/236139917-a9eac91d-3919-415a-9ff5-301f6e9b424d.png)
![image](https://user-images.githubusercontent.com/17685281/236139954-b1708574-385d-406f-912e-153404d4dbd3.png)

@Funnywolf

**Comment by FunnyWolf** [comment]
该问题的根因是msf的监听(handler)对互联网开放后,被互联网上的扫描器(网络测绘)扫描后产生大量失效的tcp连接,导致出现问题

**Comment by FunnyWolf** [comment]
该问题可以自行手动复现
- 首先在VPS上搭建viper
- 创建一个reverse_tcp类型的监听,端口为4999,假设vps ip为123.123.123.123
![image](https://user-images.githubusercontent.com/17685281/236141116-c78e4b32-b900-4e2f-b2b9-c12e873e1f7b.png)
- 在另外一台linux上运行`hping3 --flood -S -p 4999 123.123.123.123`,针对监听进行tcp flood测试
- 大概经过20秒之后,问题出现,渗透测试服务不可用
![image](https://user-images.githubusercontent.com/17685281/236141770-67629fde-c5d9-446c-b1a0-bfe65337451f.png)
![image](https://user-images.githubusercontent.com/17685281/236141810-0eff87b1-b0a8-45c0-8e64-e7d69fb2384b.png)
![image](https://user-images.githubusercontent.com/17685281/236141974-07e853d8-e110-492e-8c44-fd433853e5b3.png)
![image](https://user-images.githubusercontent.com/17685281/236142016-c0ed0b2b-3332-45c8-8272-520504ade182.png)
![image](https://user-images.githubusercontent.com/17685281/236142114-082a9626-317f-4c9f-9a54-803b9cfc13c5.png)

**Comment by gnusec** [comment]
搞个什么重启msfrpc的功能把. 不然太痛苦了.
