### ISSUE TITLE
[BUG] 凭证列表无效

### ISSUE THREAD

**Issue by ifacker** [FunnyWolf/Viper#131]
**描述Bug**
凭证列表无效

**如何复现**
在凭证列表中添加账号密码，但是添加的账号密码登录不上

**截图**
![image](https://user-images.githubusercontent.com/26481367/236460924-dd19191f-0947-4ed2-b1c1-3f730699c157.png)
![image](https://user-images.githubusercontent.com/26481367/236460979-2795bdb4-81b7-45cf-aebc-db7dbaac9f1e.png)

@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug** 凭证列表无效
> 
> **如何复现** 在凭证列表中添加账号密码，但是添加的账号密码登录不上
> 
> **截图** ![image](https://user-images.githubusercontent.com/26481367/236460924-dd19191f-0947-4ed2-b1c1-3f730699c157.png) ![image](https://user-images.githubusercontent.com/26481367/236460979-2795bdb4-81b7-45cf-aebc-db7dbaac9f1e.png)
> 
> @FunnyWolf

凭证列表添加的凭证是用来内网进行爆破用的,不是viper登录用的.
