### ISSUE TITLE
Request error 502: https://x.x.x.x:60000/api/v1/core/baseauth/ Gateway error.

### ISSUE THREAD

**Issue by HKei1nlgo** [FunnyWolf/Viper#134]
![图片](https://github.com/FunnyWolf/Viper/assets/53597861/9684bd4c-39c6-4d3e-ab32-c83cc5ff02da)
之前使用正常，突然更新以后就登录不上去了，，报这个错误，，请问是怎么回事

**Comment by FunnyWolf** [comment]
> 

后台没起来,docker compose down /docker compose up -d 重新启动一下,如果还起不来提供一下docker logs viper-c结果
