### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jinzezhi** [FunnyWolf/Viper#135]
k8s起的，一直密码错误，随便输入一个用户名提示的也是密码错误，密码输入的肯定没问题
![image](https://github.com/FunnyWolf/Viper/assets/93123422/b01348d4-7f51-453b-80e0-a5f99b7ac266)

**Comment by jinzezhi** [comment]
密码中有& 和 * 是特殊字符的原因吗

**Comment by FunnyWolf** [comment]
> 密码中有& 和 * 是特殊字符的原因吗

测试了一下,密码中有&和*不影响,还是k8s启动docker-compose.yml的问题,没有k8s的环境,无法测试.
