### ISSUE TITLE
如何创建交互式shell

### ISSUE THREAD

**Issue by lovelyjuice** [FunnyWolf/Viper#136]
有时候必须用到交互式shell，如果是msfconsole里面，可以直接shell然后用python的pty模块开启pty，但是viper好像不行？
另外，在目标已经上线viper的情况下，有没有什么办法进到msfconsole去操作viper的session呢？还是说必须得msfconsole启动一个新的handler，然后把shell转移过去？

**Comment by FunnyWolf** [comment]
> 有时候必须用到交互式shell，如果是msfconsole里面，可以直接shell然后用python的pty模块开启pty，但是viper好像不行？ 另外，在目标已经上线viper的情况下，有没有什么办法进到msfconsole去操作viper的session呢？还是说必须得msfconsole启动一个新的handler，然后把shell转移过去？

viper可以使用msfconsole的,界面上就有
1. 如果原生msfconsole能实现交互式shell那viper界面上msfconsole也能实现,但是因为 viper msfconsole<->meterpreter<->shell<->pty 这么长的链路估计是有问题,需要测试一下
2. viper可以使用msfconsole的,界面上就有,所以不需要另外起msfconsole

**Comment by FunnyWolf** [comment]
> > 有时候必须用到交互式shell，如果是msfconsole里面，可以直接shell然后用python的pty模块开启pty，但是viper好像不行？ 另外，在目标已经上线viper的情况下，有没有什么办法进到msfconsole去操作viper的session呢？还是说必须得msfconsole启动一个新的handler，然后把shell转移过去？
> 
> viper可以使用msfconsole的,界面上就有
> 
> 1. 如果原生msfconsole能实现交互式shell那viper界面上msfconsole也能实现,但是因为 viper msfconsole<->meterpreter<->shell<->pty 这么长的链路估计是有问题,需要测试一下
> 2. viper可以使用msfconsole的,界面上就有,所以不需要另外起msfconsole

经过测试,可以实现交互式,
![image](https://github.com/FunnyWolf/Viper/assets/17685281/3c56e99c-66e3-4ff9-bbfc-9bb4da5e85cd)
