### ISSUE TITLE
[BUG] 使用socks5无法访问https

### ISSUE THREAD

**Issue by 0kam1-hm** [FunnyWolf/Viper#137]
使用socks5无法访问https，然后会导致session超时卡死

**Comment by 0kam1-hm** [comment]
![2023-06-11_11-50](https://github.com/FunnyWolf/Viper/assets/54802948/f250d9eb-c4f4-4df2-bbb7-d43c545a7b21)

**Comment by FunnyWolf** [comment]
> ![2023-06-11_11-50](https://user-images.githubusercontent.com/54802948/244911125-f250d9eb-c4f4-4df2-bbb7-d43c545a7b21.png)

是否是使用viper的旧版本,使用最新版本viper无法复现问题
