### ISSUE TITLE
内网主机 ，全选，批量删除，主机过多的情况报 502错误

### ISSUE THREAD

**Issue by lonelykin** [FunnyWolf/Viper#14]
![photo_2021-04-11_01-03-56](https://user-images.githubusercontent.com/13845732/114278375-17b2d300-9a62-11eb-80ae-3efd45dc670b.jpg)

**Comment by FunnyWolf** [comment]
虽然没有复现,但是我猜测应该是delete请求的参数太长导致超出浏览器限制了,这个后续采用拆分请求的方式规避
