### ISSUE TITLE
[BUG] 通过socks访问https导致会话异常

### ISSUE THREAD

**Issue by 0kam1-hm** [FunnyWolf/Viper#142]
**描述Bug**
通过socks访问https导致会话异常

**如何复现**
请说明如何复现Bug:
1. 点击内网代理
2. 新增代理
3. 通过代理访问内网https网站
4. Bug出现了，会话异常

**截图**
![2023-07-27_01-25](https://github.com/FunnyWolf/Viper/assets/54802948/dc82e8e0-7240-4235-9fa7-12f1bdf7417f)

@Funnywolf

**Comment by 0kam1-hm** [comment]
最新版本 v1.6.1 20230709

**Comment by FunnyWolf** [comment]
> 最新版本 v1.6.1 20230709

测试了一下功能是正常的,极有可能不是https问题,而是网络慢(VPS到马之间)导致的msf bug

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/143

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/143
