### ISSUE TITLE
全网搜索引擎用不了

### ISSUE THREAD

**Issue by shirenweifa** [FunnyWolf/Viper#144]
<img width="921" alt="image" src="https://github.com/FunnyWolf/Viper/assets/80664877/7edc2fd4-39e0-41c1-abbb-93e6d5eb8016">

**Comment by shirenweifa** [comment]
<img width="425" alt="image" src="https://github.com/FunnyWolf/Viper/assets/80664877/3dcd60b0-0806-4183-957d-ccda97242361">
<img width="203" alt="image" src="https://github.com/FunnyWolf/Viper/assets/80664877/6215ae47-e103-4698-8885-330690d3057b">
信息收集只有一个，但是加载模块加载了100个，没显示出来是怎么回事

**Comment by FunnyWolf** [comment]
> <img alt="image" width="921" src="https://user-images.githubusercontent.com/80664877/257391244-7edc2fd4-39e0-41c1-abbb-93e6d5eb8016.png">

没有配置key

**Comment by FunnyWolf** [comment]
> <img alt="image" width="425" src="https://user-images.githubusercontent.com/80664877/257400706-3dcd60b0-0806-4183-957d-ccda97242361.png"> <img alt="image" width="203" src="https://user-images.githubusercontent.com/80664877/257400739-6215ae47-e103-4698-8885-330690d3057b.png"> 信息收集只有一个，但是加载模块加载了100个，没显示出来是怎么回事

需要点击session所在行的按钮才能显示session的模块
https://www.yuque.com/vipersec/help/lezyt4
