### ISSUE TITLE
viper最新版没有报错但console无法使用模块面板有

### ISSUE THREAD

**Issue by Logan147** [FunnyWolf/Viper#15]
viper最新版没有报错但console无法使用，模块面板一直显示nodata，运行生成的payload监听模块也没反应。

![屏幕截图 2021-04-12 06:07:40](https://user-images.githubusercontent.com/58822519/114307490-6d46b880-9b12-11eb-8050-02c11a7817ca.png)

**Comment by Logan147** [comment]
谁来救救我

**Comment by Logan147** [comment]
msf接口日志什么也没有但能生成payload
![屏幕截图 2021-04-12 06:36:42](https://user-images.githubusercontent.com/58822519/114308402-69b53080-9b16-11eb-9383-037f0afae0aa.png)

**Comment by FunnyWolf** [comment]
> sf接口日志什么也没有但能生

应该是后台服务没有起来,启动方法是docker-compose up -d,.日志可以贴全一点

**Comment by Logan147** [comment]
好的，我试一试

**Comment by Logan147** [comment]
puma.log 还是没有内容
![屏幕截图 2021-04-12 06:36:42](https://user-images.githubusercontent.com/58822519/114337730-4032ee00-9b84-11eb-83b8-89a03c684261.png)
![屏幕截图 2021-04-12 06:07:40](https://user-images.githubusercontent.com/58822519/114337738-43c67500-9b84-11eb-8f63-0c5b05fdb827.png)

**Comment by Logan147** [comment]
这是error.log的内容
![屏幕截图 2021-04-12 19:44:41](https://user-images.githubusercontent.com/58822519/114337881-87b97a00-9b84-11eb-9bff-d5fc77e4915d.png)
这是puma.log的内容
![屏幕截图 2021-04-12 19:43:59](https://user-images.githubusercontent.com/58822519/114337921-9869f000-9b84-11eb-9764-75129139a192.png)

这是viperpython.log的内容
![屏幕截图 2021-04-12 19:46:51](https://user-images.githubusercontent.com/58822519/114338079-ea127a80-9b84-11eb-9efe-bbb4671a1e85.png)
![屏幕截图 2021-04-12 19:47:11](https://user-images.githubusercontent.com/58822519/114338086-ec74d480-9b84-11eb-9fec-2fff59485150.png)
![屏幕截图 2021-04-12 19:47:22](https://user-images.githubusercontent.com/58822519/114338097-ef6fc500-9b84-11eb-82bf-f757c55daa7e.png)

**Comment by Logan147** [comment]
他显示后台服务启动成功但是还是一直no data 不能用console

**Comment by FunnyWolf** [comment]
> 他显示后台服务启动成功但是还是一直no data 不能用console

还是启动方法不对,后台在不断重启,应该是没有按照手册安装,现在信息无法定位是什么原因导致的

**Comment by Logan147** [comment]
我直接用apt-get安装的docker.io和docker-compose会不会是这个原因

**Comment by Logan147** [comment]
我删除docker和docker-compose后按照手册重新安装但没有反应
![屏幕截图 2021-04-13 00:36:00](https://user-images.githubusercontent.com/58822519/114365568-2c4fb200-9bad-11eb-802e-6710f8c551c0.png)

**Comment by Logan147** [comment]
这次我又重装了一次不重启了但还是不显示console一直no data
![屏幕截图 2021-04-13 00:54:43](https://user-images.githubusercontent.com/58822519/114368403-f7912a00-9baf-11eb-8f46-5fbf01ccbb8d.png)
![屏幕截图 2021-04-13 00:55:05](https://user-images.githubusercontent.com/58822519/114368420-fb24b100-9baf-11eb-915b-050f5596d244.png)

**Comment by FunnyWolf** [comment]
> 这次我又重装了一次不重启了但还是不显示console一直no data
> ![屏幕截图 2021-04-13 00:54:43](https://user-images.githubusercontent.com/58822519/114368403-f7912a00-9baf-11eb-8f46-5fbf01ccbb8d.png)
> ![屏幕截图 2021-04-13 00:55:05](https://user-images.githubusercontent.com/58822519/114368420-fb24b100-9baf-11eb-915b-050f5596d244.png)

不要用127.0.0.1,前端代码对127有特殊处理
