### ISSUE TITLE
[BUG]Request error 502: https://**ip**:60000/api/v1/core/baseauth/ Gateway error.

### ISSUE THREAD

**Issue by JoeQinOvO** [FunnyWolf/Viper#151]
**复现步骤**
几乎是突然出现，无法登陆，只要点击登陆就会弹出，现在已经完全无法登陆

**截图**
![image](https://github.com/FunnyWolf/Viper/assets/104407735/8dfca5d8-12ea-4e35-922a-f12c3e8de45a)

@Funnywolf

目前我做过的尝试有：
1.升级viper（原本是0719版本，现在是8月版本），无效
2.docker-compose stop/start，无效
3.docker-compose down /docker compose up -d ,无效
4.最狠的：我在服务器第一次安装viper之前留了一个快照，直接回滚到安装viper之前的版本。
然后从零开始重新安装f8x和viper，令我吃惊的是，还是出现了这个情况。

**Comment by FunnyWolf** [comment]
需要登录服务器看一下,https://www.yuque.com/vipersec/install/olg1ua最后有我联系方式

**Comment by JoeQinOvO** [comment]
经过作者的提示，这种情况很有可能跟地区网络有关？我在杭州的网络就会出现这种问题，与此同时，用湖北的电脑登录，就是正常的了，目前不清楚发生这种情况的原因，所以出现这种情况的师傅们，可以试试切换网络环境试试

**Comment by FunnyWolf** [comment]
502 错误参考上述JoeWinOvO的回答,504是viperpython后台问题
