### ISSUE TITLE
[BUG]上线多台主机使用同一监听时，监听莫名消失

### ISSUE THREAD

**Issue by ppofp** [FunnyWolf/Viper#154]
**复现步骤**
1、对三百台主机内网进行上线，上线40台左右后监听全部消失
2.、监听界面所有监听全部消失

@Funnywolf

**Comment by ppofp** [comment]
> > **复现步骤** 1、对三百台主机内网进行上线，上线40台左右后监听全部消失 2.、监听界面所有监听全部消失
> > @FunnyWolf
> 
> 性能问题,内存多大

2GB

**Comment by FunnyWolf** [comment]
> > > **复现步骤** 1、对三百台主机内网进行上线，上线40台左右后监听全部消失 2.、监听界面所有监听全部消失
> > > @FunnyWolf
> > 
> > 
> > 性能问题,内存多大
> 
> 2GB

需要具体日志才能定位问题,请提供一下

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/vipermsf/commit/111040bbfa4663200703012c1856a7f4b3ccd205
