### ISSUE TITLE
bash f8x -viper不能使用了

### ISSUE THREAD

**Issue by xiaoming-king** [FunnyWolf/Viper#165]
bash f8x -viper
![image](https://github.com/FunnyWolf/Viper/assets/65775367/bf2f385e-bb2d-4ce3-b498-904c9d83a123)

**Comment by FunnyWolf** [comment]
已经转给隔壁的f8x@No-Github

**Comment by FunnyWolf** [comment]
https://github.com/ffffffff0x/f8x/issues/38
