### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kgg-moon** [FunnyWolf/Viper#167]
**复现步骤**
1. 生成载荷后在靶机执行
2. 靶机运行完后进程中存在相关exe，但是viper无新建session
3. 实时输出里出现新session连接信息但是无新建session

**截图**
Bug截图.
![image](https://github.com/FunnyWolf/Viper/assets/74181372/b731c818-52bc-4e39-b1d6-061f50c0ded1)
![image](https://github.com/FunnyWolf/Viper/assets/74181372/7bc2b0d2-a1b8-4613-a39e-a1b4478a6026)

@Funnywolf

**Comment by FunnyWolf** [comment]
> 

反馈一下日志吧

**Comment by FunnyWolf** [comment]
https://www.yuque.com/vipersec/install/py5fqc

**Comment by Kgg-moon** [comment]
坏，昨晚docker出了问题解决不了，刚把整个vps重装然后重下了viper

**Comment by Kgg-moon** [comment]
后续有问题再发出来研究一下吧
