### ISSUE TITLE
[BUG]隔断时间就全部掉线，msfrpcd未启动

### ISSUE THREAD

**Issue by possib1e** [FunnyWolf/Viper#17]
ubuntu18, 2h4g，隔断时间就全部掉线，查看docker日志是显示[x] msfrpcd未启动，面板显示渗透服务不可用，更新渗透服务，重载所有模块无法解决，重启docker有时候要好几个小时才会重新上线。

**Comment by FunnyWolf** [comment]
> ubuntu18, 2h4g，隔断时间就全部掉线，查看docker日志是显示[x] msfrpcd未启动，面板显示渗透服务不可用，更新渗透服务，重载所有模块无法解决，重启docker有时候要好几个小时才会重新上线。

反馈一下日志信息,https://www.yuque.com/vipersec/faq/is0ypq

**Comment by FunnyWolf** [comment]
问题发生原因很可能是由于开放reverse_tcp及socks代理到外网的常用端口(80,1080),导致内存占用飙升,服务崩溃.
由于ruby本身的gc机制,暂时没有技术手段规避.使用以下commit进行提示

https://github.com/FunnyWolf/viperjs/commit/8b35c9a58de491db28e30c6e098eeba63d1ce35f#diff-ff17c59812c160dce30f79469d01bfe98f0188d86da10d1d3d77fb6499a0b2e5
