### ISSUE TITLE
[FEATURE]自动定时执行模块或者执行内存加载的脚本功能

### ISSUE THREAD

**Issue by xizyy** [FunnyWolf/Viper#170]
shell多起来后如何自动化管理十分麻烦。
CS可以通过服务端加载插件实现。
在viper没找到合适的实现方法，要不考虑下整一个让VIPER更加强大。

**Comment by FunnyWolf** [comment]
viper有相关的自动化功能,参考如下文档
https://www.yuque.com/vipersec/help/gh60e1
只不过用的少所以没有进行优化,如果推荐的场景进一步回复.

**Comment by FunnyWolf** [comment]
@xizyy

**Comment by xizyy** [comment]
感谢回复，已有的这个自动编排是在获取新session时执行。一般用在获取初始权限后的自动信息收集、自动提权、维权。而在需要持续监控session状态，持续收集信息的场景下：比如管理员登陆提醒，文件变动提醒，以及更多的需要持续观察管理员操作以场景下，需要一个能定时执行模块或者命令的东西。但是为了减少暴露风险这个定时执行不能使用已攻陷的服务器上的计划任务。废话有点多。。。一句话概括就是，自动编排能加个定时执行就好了

**Comment by FunnyWolf** [comment]
> 

@xizyy 
理解了,这个可以拆分成两块来做
1. (管理员登陆提醒，文件变动提醒，以及更多的需要持续观察管理员操作以场景下),这个需要编写viper的模块来实现每一个功能,现有的模块框架已经很成熟,可以做.需要进一步分析的就是具体功能是什么样的,具体监控指定文件还是用户自定义文件
2. 自动编排加个定时执行的功能,这个是新功能,可以做.
如果有更详细的需求可以根据以下联系方式联系我
https://www.yuque.com/vipersec/install/py5fqc
