### ISSUE TITLE
[BUG]RPGMSG黑屏

### ISSUE THREAD

**Issue by P0H1ng** [FunnyWolf/Viper#173]
**复现步骤**
似乎是服务器重开后，就一片黑屏，可是执行信息还是会跑，求解

**截图**
![image](https://github.com/FunnyWolf/Viper/assets/53214411/accfe39d-3437-4c04-8bae-d9069d7d28b1)

@Funnywolf

**Comment by FunnyWolf** [comment]
@P0H1ng 请反馈日志

**Comment by P0H1ng** [comment]
不知道要丢哪个，5个都丢上来了
https://t.wss.ink/f/c69ixmzpwg3

**Comment by FunnyWolf** [comment]
> @FunnyWolf 不知道要丢哪个，5个都丢上来了 https://t.wss.ink/f/c69ixmzpwg3

看日志应该不是最新版本,日志补全,可以更新最新版本试一下
https://www.yuque.com/vipersec/install/qofhby

**Comment by P0H1ng** [comment]
更新后还是一样。。

**Comment by FunnyWolf** [comment]
> 更新后还是一样。。

日志再发一下

**Comment by FunnyWolf** [comment]
@P0H1ng

**Comment by P0H1ng** [comment]
https://t.wss.ink/f/c6ja81x80w3
更新后的日志

**Comment by FunnyWolf** [comment]
> https://t.wss.ink/f/c6ja81x80w3 更新后的日志

从日志里面看是没有问题的,或者说从日志里面看不出问题

**Comment by P0H1ng** [comment]
结果右上角切换英文再切回来中文就好了。。昏。
