### ISSUE TITLE
[BUG]   内存执行C#可执行文件实时输出空白

### ISSUE THREAD

**Issue by kokxxoo** [FunnyWolf/Viper#177]
**复现步骤**
1. XXX
![QQ图片20230914215418](https://github.com/FunnyWolf/Viper/assets/17762843/50293514-1d57-45f0-92c3-f1017cbae424)

2. YYY

**截图**
Bug截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
> **复现步骤**
> 
> 1. XXX
>    ![QQ图片20230914215418](https://user-images.githubusercontent.com/17762843/267999606-50293514-1d57-45f0-92c3-f1017cbae424.png)
> 2. YYY
> 
> **截图** Bug截图.
> 
> @FunnyWolf

请提供执行的C#文件

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/vipermsf/commit/eceeb6b416ecedc5dd5791b4dd5f345b5918c4f8
