### ISSUE TITLE
[BUG]502 Bad Gateway 登不上去

### ISSUE THREAD

**Issue by kokxxoo** [FunnyWolf/Viper#184]
**复现步骤**
1. XXX
2. YYY

**截图**
[-] Redis 启动失败,缓存的Token未清理
[+] 修改密码完成,新密码为: 123123
[*] 重启redis服务
[*] 重启redis完成
[*] 启动redis服务
[*] 启动msfrpcd服务
[*] 启动daphne主服务
[*] 启动VIPER主服务
[*] 启动proxy服务
[+] Mitmproxy: http://vpsip:28888
[+] root:123123
[*] 启动nginx服务
 -------------- 检查服务状态 ----------------
[+] nginx运行中
[+] redis运行中
[x] msfrpcd未启动
[+] uwsgi运行中
[+] daphne服务运行中
 -------------- 检查服务状态 ----------------
[+] nginx运行中
[+] redis运行中
[+] msfrpcd运行中
[+] uwsgi运行中
[+] daphne服务运行中
[+] 启动完成

@Funnywolf

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/178
