### ISSUE TITLE
不停的重复上线和死亡

### ISSUE THREAD

**Issue by xigagas** [FunnyWolf/Viper#194]
**截图**
Bug截图.

不停的重复上线和死亡  session都干到2400多了
![photo_2023-12-18_21-57-17](https://github.com/FunnyWolf/Viper/assets/139865587/9b2f5612-867e-448a-9a20-d25eb18e8a25)
![photo_2023-12-18_21-57-43](https://github.com/FunnyWolf/Viper/assets/139865587/642e3426-068b-4c78-9aff-3f0d179c209b)
![photo_2023-12-18_21-58-03](https://github.com/FunnyWolf/Viper/assets/139865587/342932e4-482b-4609-8ac4-70c6ebea9525)
![photo_2023-12-18_22-00-00](https://github.com/FunnyWolf/Viper/assets/139865587/076366b0-baf9-4e62-bfb1-b62c1430e7a8)

**Comment by FunnyWolf** [comment]
这个issus 会不会导致这个issus出现(内存增长) https://github.com/FunnyWolf/Viper/issues/193 @xigagas

**Comment by xigagas** [comment]
会 直到宕机，

**Comment by xigagas** [comment]
这个会影响卡住新上线的session,木马新上线的会一直卡主不回显，然后也重复上线。

**Comment by FunnyWolf** [comment]
> 这个会影响卡住新上线的session,木马新上线的会一直卡主不回显，然后也重复上线。

https://www.yuque.com/vipersec/install/py5fqc
方便的话联系我一下看一下细节

**Comment by 0day4day** [comment]
同上，经常出现这种情况，求修复。

**Comment by telegramerror** [comment]
遇到了同样的问题，好像都是linux服务器，viper真是一个很好的项目，可惜我知识不够帮不上忙
