### ISSUE TITLE
[BUG] （session堵住了）卡session，执行viper的马上线有提示上线，但没session在显示框上

### ISSUE THREAD

**Issue by 0day4day** [FunnyWolf/Viper#195]
具体情况是这样的，经常会出现我打开木马上线session，下面日志显示有session上线，而且是不断请求，举个例子如下图
就是不停的上线，而且我经过测试本地机子也会卡session，他们好像堵住了一样，这个时候，你必须docker restart 就是重启一下docker那个程序然后重新打开监听，才能恢复正常，请求修复
![image](https://github.com/FunnyWolf/Viper/assets/155231248/69b5c54a-03a6-410e-9727-03fd150cc44e)

**Comment by 0day4day** [comment]
重启之后，之前堵住的session，就是下面这个不断请求的就正常回显到session里面的，但是每次都要重启，太麻烦了

**Comment by FunnyWolf** [comment]
> 重启之后，之前堵住的session，就是下面这个不断请求的就正常回显到session里面的，但是每次遇到这种情况都要重启，太麻烦了，有没有简单的按钮重置下，或者啥方法，感谢作者了！

是什么类型的session有这种情况,windows/linux/mac?

**Comment by FunnyWolf** [comment]
[0-day.us/img/doc/10.doc](https://0-day.us/img/doc/10.doc)

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/194

**Comment by FunnyWolf** [comment]
@0day4day

**Comment by 0day4day** [comment]
> > 重启之后，之前堵住的session，就是下面这个不断请求的就正常回显到session里面的，但是每次遇到这种情况都要重启，太麻烦了，有没有简单的按钮重置下，或者啥方法，感谢作者了！
> 
> 是什么类型的session有这种情况,windows/linux/mac?

他出现卡session的情况之后，不管执行任何类型的系统木马windows/linux/mac都只会有图片上的显示session上线，但是实际上并没有上线到图片上，而且sessions 也没有看到对应上线的session ID，就是像堵住了一样，后面的所有session都卡住了。但是我docker restart了之后，他们又全部正常上线 sessions也能查看到

**Comment by 0day4day** [comment]
这种情况非常频繁，一般情况，1-3天出现一次。现在基本日常重启docker

**Comment by DamnVanish** [comment]
我也遇到了这种问题，显示有session但是没有图标
