### ISSUE TITLE
[BUG]在arm的CPU平台上，debian系统下dokcer启动不成功

### ISSUE THREAD

**Issue by ppofp** [FunnyWolf/Viper#197]
如题，报错如下，应该viper不支持arm架构，不知道能否提供支持
docker-compose up
viper-c is up-to-date
Attaching to viper-c
viper-c  | exec /usr/bin/viper: exec format error

**Comment by FunnyWolf** [comment]
viper暂时没有支持arm的计划.

**Comment by myz2010** [comment]
就一下阿哥们      我树莓派快哭死了
