### ISSUE TITLE
[BUG] 上线session后viper直接崩溃，web界面一直黑屏。JS console报错 13M那个js文件

### ISSUE THREAD

**Issue by 0day4day** [FunnyWolf/Viper#199]
aught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B~signo%2C%20~bt_locations%2C%20~mesg%2C%20~bt%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

![image](https://github.com/FunnyWolf/Viper/assets/155231248/a7f4702d-e830-4fd6-a033-4b1d410f668b)

不管重启还是登陆，都是黑屏。我怀疑是数据的问题，每次都是这个console报错

![image](https://github.com/FunnyWolf/Viper/assets/155231248/fa308bd0-2555-4238-bd97-097f4dc7b842)

并且数据库文件中还多了个文件 ， 如下图

![image](https://github.com/FunnyWolf/Viper/assets/155231248/6099a0c0-4cf5-48d9-addc-89aa8c4ce6c1)

最终解决问题的方式就是删了那个多余的数据库里的文件。就恢复正常

**Comment by FunnyWolf** [comment]
该问题已经在最新版本修复 https://github.com/FunnyWolf/Viper/issues/191

**Comment by FunnyWolf** [comment]
@0day4day 是最新版本吗

**Comment by 0day4day** [comment]
> @0day4day 是最新版本吗

是最新版
如下图
<html>
<body>

平台版本2023-12-07-13-44-18 | 最新版本2023-12-03-13-44-27 |  
-- | -- | --



<body>
<table style="box-sizing: border-box; border-collapse: collapse; width: 1768px; table-layout: fixed;"><tbody style="box-sizing: border-box;"><tr class="ant-descriptions-row" style="box-sizing: border-box; border-bottom: none;"><td class="ant-descriptions-item" colspan="1" style="box-sizing: border-box; padding-bottom: 8px; vertical-align: top; color: rgba(255, 255, 255, 0.85); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(20, 20, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="ant-descriptions-item-container" style="box-sizing: border-box; display: flex;"><span class="ant-descriptions-item-label" style="box-sizing: border-box; color: rgba(255, 255, 255, 0.85); font-weight: 400; font-size: 14px; line-height: 1.5715; text-align: start; display: inline-flex; align-items: baseline;">平台版本</span><span class="ant-descriptions-item-content" style="box-sizing: border-box; display: inline-flex; flex: 1 1 0%; color: rgba(255, 255, 255, 0.85); font-size: 14px; line-height: 1.5715; word-break: break-word; overflow-wrap: break-word; align-items: baseline;"><span class="ant-tag ant-tag-blue" style="box-sizing: border-box; color: rgb(60, 154, 232); font-variant: tabular-nums; list-style: none; display: inline-block; height: auto; margin: 0px 8px 0px 0px; padding: 0px 7px; font-size: 12px; line-height: 20px; white-space: nowrap; background: rgb(17, 29, 44); border: 1px solid rgb(21, 57, 91); border-radius: 6px; opacity: 1; transition: all 0.3s ease 0s;">2023-12-07-13-44-18</span></span></div></td><td class="ant-descriptions-item" colspan="1" style="box-sizing: border-box; padding-bottom: 8px; vertical-align: top; color: rgba(255, 255, 255, 0.85); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(20, 20, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="ant-descriptions-item-container" style="box-sizing: border-box; display: flex;"><span class="ant-descriptions-item-label" style="box-sizing: border-box; color: rgba(255, 255, 255, 0.85); font-weight: 400; font-size: 14px; line-height: 1.5715; text-align: start; display: inline-flex; align-items: baseline;">最新版本</span><span class="ant-descriptions-item-content" style="box-sizing: border-box; display: inline-flex; flex: 1 1 0%; color: rgba(255, 255, 255, 0.85); font-size: 14px; line-height: 1.5715; word-break: break-word; overflow-wrap: break-word; align-items: baseline;"><div class="ant-space ant-space-horizontal ant-space-align-center" style="box-sizing: border-box; display: inline-flex; align-items: center; gap: 8px;"><div class="ant-space-item" style="box-sizing: border-box;"><span class="ant-tag ant-tag-blue" style="box-sizing: border-box; color: rgb(60, 154, 232); font-variant: tabular-nums; list-style: none; display: inline-block; height: auto; margin: 0px 8px 0px 0px; padding: 0px 7px; font-size: 12px; line-height: 20px; white-space: nowrap; background: rgb(17, 29, 44); border: 1px solid rgb(21, 57, 91); border-radius: 6px; opacity: 1; transition: all 0.3s ease 0s;">2023-12-03-13-44-27</span></div><div class="ant-space-item" style="box-sizing: border-box;"><button type="button" class="ant-btn ant-btn-default ant-btn-sm ant-btn-icon-only" ant-click-animating-without-extra-node="false" style="box-sizing: border-box; touch-action: manipulation; margin: 0px; color: rgba(255, 255, 255, 0.85); font-size: 14px; font-family: inherit; line-height: 1.5715; overflow: visible; text-transform: none; appearance: button; position: relative; display: inline-block; font-weight: 400; white-space: nowrap; text-align: center; box-shadow: rgba(0, 0, 0, 0.016) 0px 2px 0px; cursor: pointer; transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1) 0s; user-select: none; height: 24px; padding: 0px; border-radius: 6px; border: 1px solid rgb(67, 67, 67); background: transparent; outline: 0px; width: 48px; vertical-align: -3px;"><span role="img" aria-label="sync" class="anticon anticon-sync" style="box-sizing: border-box; display: flex; color: inherit; font-style: normal; line-height: 1; text-align: center; text-transform: none; vertical-align: -0.125em; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased; align-items: center; font-size: 14px; justify-content: center; transition: margin-left 0.3s cubic-bezier(0.645, 0.045, 0.355, 1) 0s;"><svg viewBox="64 64 896 896" focusable="false" data-icon="sync" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M168 504.2c1-43.7 10-86.1 26.9-126 17.3-41 42.1-77.7 73.7-109.4S337 212.3 378 195c42.4-17.9 87.4-27 133.9-27s91.5 9.1 133.8 27A341.5 341.5 0 01755 268.8c9.9 9.9 19.2 20.4 27.8 31.4l-60.2 47a8 8 0 003 14.1l175.7 43c5 1.2 9.9-2.6 9.9-7.7l.8-180.9c0-6.7-7.7-10.5-12.9-6.3l-56.4 44.1C765.8 155.1 646.2 92 511.8 92 282.7 92 96.3 275.6 92 503.8a8 8 0 008 8.2h60c4.4 0 7.9-3.5 8-7.8zm756 7.8h-60c-4.4 0-7.9 3.5-8 7.8-1 43.7-10 86.1-26.9 126-17.3 41-42.1 77.8-73.7 109.4A342.45 342.45 0 01512.1 856a342.24 342.24 0 01-243.2-100.8c-9.9-9.9-19.2-20.4-27.8-31.4l60.2-47a8 8 0 00-3-14.1l-175.7-43c-5-1.2-9.9 2.6-9.9 7.7l-.7 181c0 6.7 7.7 10.5 12.9 6.3l56.4-44.1C258.2 868.9 377.8 932 512.2 932c229.2 0 415.5-183.7 419.8-411.8a8 8 0 00-8-8.2z"></path></svg></span></button></div></div></span></div></td><td class="ant-descriptions-item" colspan="1" style="box-sizing: border-box; padding-bottom: 8px; vertical-align: top; color: rgba(255, 255, 255, 0.85); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(20, 20, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="ant-descriptions-item-container" style="box-sizing: border-box; display: flex;"><br class="Apple-interchange-newline">
</body>
</html>


一直在支持最新版

**Comment by FunnyWolf** [comment]
> > @0day4day 是最新版本吗
> 
> 是最新版 如下图
> 
> 平台版本2023-12-07-13-44-18 | 最新版本2023-12-03-13-44-27 |   -- | -- | --
> 平台版本2023-12-07-13-44-18
> 最新版本
> 2023-12-03-13-44-27
> 
> 一直在支持最新版

这个如果复现了可以提供一下dump.rdb文件
