### ISSUE TITLE
执行系统命令失败

### ISSUE THREAD

**Issue by mmioimm** [FunnyWolf/Viper#2]
环境 win7 64位 监听windows/x64/meterpreter_reverse_tcp，执行 shell whoami，报错：
![image](https://user-images.githubusercontent.com/19258899/103848040-758af400-50dc-11eb-8a63-ea4782f8b0a9.png)

**Comment by FunnyWolf** [comment]
> 环境 win7 64位 监听windows/x64/meterpreter_reverse_tcp，执行 shell whoami，报错：
> ![image](https://user-images.githubusercontent.com/19258899/103848040-758af400-50dc-11eb-8a63-ea4782f8b0a9.png)

生成的session没有正确加载stdapi.dll,可以尝试重新生成一个session,如果重复出现,可能是杀软或os环境特殊.

**Comment by hkxueqi** [comment]
测试目标一：win10 1809 x64  无杀软，关了自带杀软/防火墙。
测试目标2：centos 7.8 
shell >  whoami
[-] Error: Command -- whoami is nonsupport
[-] undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__Manage__Execute::MetasploitModule:0x00007feb9a45e718>

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/b8278c19787d2c192726320b6888d228d009cb42
