### ISSUE TITLE
持久化不行，全给360报毒了

### ISSUE THREAD

**Issue by zhengjingyuan3855** [FunnyWolf/Viper#20]

**Comment by FunnyWolf** [comment]
作者水品有限,当前已知的所有需要动注册表的持久化方法都过不了360,而且也没有发现那种方式能绕过360的监控

**Comment by zhengjingyuan3855** [comment]
> 作者水品有限,当前已知的所有需要动注册表的持久化方法都过不了360,而且也没有发现那种方式能绕过360的监控

那啥，平台自带的msfconsole能加载模块吗？希望开通此功能

**Comment by FunnyWolf** [comment]
> > 作者水品有限,当前已知的所有需要动注册表的持久化方法都过不了360,而且也没有发现那种方式能绕过360的监控
> 
> 那啥，平台自带的msfconsole能加载模块吗？希望开通此功能

msf自带的模块msfconsole都可以使用,和命令行版本的功能一样,如果你要加载自己写的msf模块,就需要把msf模块上传到docker容器内部的/root/.msf4/module/目录中

**Comment by zhengjingyuan3855** [comment]
> > > 作者水品有限,当前已知的所有需要动注册表的持久化方法都过不了360,而且也没有发现那种方式能绕过360的监控
> > 
> > 
> > 那啥，平台自带的msfconsole能加载模块吗？希望开通此功能
> 
> msf自带的模块msfconsole都可以使用,和命令行版本的功能一样,如果你要加载自己写的msf模块,就需要把msf模块上传到docker容器内部的/root/.msf4/module/目录中,然后再msfconsole 中执行 reload_all

好，谢谢，好项目点个赞
