### ISSUE TITLE
[BUG] session异常离线后，端口转发功能失效

### ISSUE THREAD

**Issue by JoeQinOvO** [FunnyWolf/Viper#200]
**复现步骤**
1. 对某session开启端口转发，此时功能正常。（测试使用reverse_https的x64 stageless）
2. **未关闭端口转发，但session离线**（我测试了关机、taskkill，手动离线session未测试）
3. 从现在起，端口转发功能将失效_(不论是否在“内网代理”面板删除这个旧的端口转发)_，具体体现为：
4. 对任意session开启端口转发，各处提示均为正常，但实际已经无法访问vps_ip:port。

简单复现：python起一个httpserver，按步骤复现即可。
初步解决方法：docker重启viper服务可以恢复

@Funnywolf

_可能的原因：端口转发服务没有考虑到session掉线的情况，未处理抛出的异常？_

**新年快乐**

**Comment by FunnyWolf** [comment]
> **复现步骤**
> 
> 1. 对某session开启端口转发，此时功能正常。（测试使用reverse_https的x64 stageless）
> 2. **未关闭端口转发，但session离线**（我测试了关机、taskkill，手动离线session未测试）
> 3. 从现在起，端口转发功能将失效_(不论是否在“内网代理”面板删除这个旧的端口转发)_，具体体现为：
> 4. 对任意session开启端口转发，各处提示均为正常，但实际已经无法访问vps_ip:port。
> 
> 简单复现：python起一个httpserver，按步骤复现即可。 初步解决方法：docker重启viper服务可以恢复
> 
> @FunnyWolf
> 
> _可能的原因：端口转发服务没有考虑到session掉线的情况，未处理抛出的异常？_
> 
> **新年快乐**

测试了一下,应该是session关闭时没有清理端口转发的配置导致的
