### ISSUE TITLE
[BUG]office宏钓鱼文档这里有bug

### ISSUE THREAD

**Issue by thebatmanfuture** [FunnyWolf/Viper#204]
![image](https://github.com/FunnyWolf/Viper/assets/75312962/82996613-d047-4f23-9016-434748582089)
这里我选的是反弹https的上线payload，得到docm后
![image](https://github.com/FunnyWolf/Viper/assets/75312962/e6eedeff-91da-4c2d-ba05-dfec760ef3ed)
![image](https://github.com/FunnyWolf/Viper/assets/75312962/43fa983d-6f55-4014-896e-a9f0faab8002)
通过另存为得到了启用了宏编辑的，启动之后无法上线session
![image](https://github.com/FunnyWolf/Viper/assets/75312962/c11af400-6e2c-4425-8fa5-a3338e6e4be2)
我这里点击运行也不上线，另外一个功能"伪造成Word文档的exe文件"也无法上线

**Comment by FunnyWolf** [comment]
关闭AV后两个模块功能都正常,AV查杀问题
