### ISSUE TITLE
[BUG]Viper 生成监听exe无法上线端口开通无问题,安全策略无问题

### ISSUE THREAD

**Issue by JishiTeam-J1wa** [FunnyWolf/Viper#208]
**复现步骤**
1. XXX
2. YYY

**截图**
Bug截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
所有类型payload都无法上线还是某一种payload无法上线?

**Comment by JishiTeam-J1wa** [comment]
所有的都无法上线,甚至没有对服务器的链接进程因为我电脑线路存在EDR一点流量都没有

**Comment by FunnyWolf** [comment]
> 所有的都无法上线,甚至没有对服务器的链接进程因为我电脑线路存在EDR一点流量都没有

杀软问题无解,可以试一下是不是能给自己vps上线来判断viper本身是不是有问题

**Comment by JishiTeam-J1wa** [comment]
![图片](https://github.com/FunnyWolf/Viper/assets/54792624/5135178f-6153-440f-8ca7-dd051154fdc0)
这是vps自上线 ,viper并无反应
这是viper的监听页面
![图片](https://github.com/FunnyWolf/Viper/assets/54792624/a587b2d2-8bd7-4c66-a0cb-d1f48cd4f2ea)
这是宝塔安全的端口开放情况
![图片](https://github.com/FunnyWolf/Viper/assets/54792624/069e78c7-488d-4556-8584-5e9299aa8321)

**Comment by JishiTeam-J1wa** [comment]
这是viper的docker容器日志
![图片](https://github.com/FunnyWolf/Viper/assets/54792624/efea5679-1976-4655-a449-18375d04759d)

**Comment by JishiTeam-J1wa** [comment]
这是viper的docker容器日志
![图片](https://github.com/FunnyWolf/Viper/assets/54792624/efea5679-1976-4655-a449-18375d04759d)

**Comment by FunnyWolf** [comment]
> 这是viper的docker容器日志 ![图片](https://private-user-images.githubusercontent.com/54792624/325463339-efea5679-1976-4655-a449-18375d04759d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjU4NDYsIm5iZiI6MTcxNDAyNTU0NiwicGF0aCI6Ii81NDc5MjYyNC8zMjU0NjMzMzktZWZlYTU2NzktMTk3Ni00NjU1LWE0NDktMTgzNzVkMDQ3NTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2MTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NmMxYzlmMmRjYWE3ZmM0MDlmMWRlNDM3ZTFkNzMxZDA0YTNlNTYzOTUxNDAzYWI2MTkyNzE5NTY3ZDEzMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.31UU4MebEBACoaC4Rg5ZodujEROnFxaFfEmbs7f5hoo)

应该还是防火墙问题,可以试一下reverse_tcp给vps上线,或者浏览器访问一下reverse_https的监听
