### ISSUE TITLE
[BUG] 无法新建监听

### ISSUE THREAD

**Issue by cvi-Qing** [FunnyWolf/Viper#209]
**复现步骤**
这个问题突然出现的，主要是再使用一段时间之后就会出现无法新增监听或者某个东西报错无法使用，我需要每次都重新启动，或者重新安装才有效果，但是使用一会或者几天之后又出现这个问题，想求助一下
，感谢作者
**截图**
Bug截图.

配置信息：
不知道是不是跟机器配置有关系
![image](https://github.com/FunnyWolf/Viper/assets/86301063/cfed2766-b887-4c1b-8146-23b3d582f790)

![image](https://github.com/FunnyWolf/Viper/assets/86301063/1eb14f7c-52c9-4e4a-8a52-c65b21873e6b)
![image](https://github.com/FunnyWolf/Viper/assets/86301063/b693619d-06fd-4f6b-8b43-bcd9bee31d6c)
@Funnywolf

**Comment by FunnyWolf** [comment]
> **复现步骤** 这个问题突然出现的，主要是再使用一段时间之后就会出现无法新增监听或者某个东西报错无法使用，我需要每次都重新启动，或者重新安装才有效果，但是使用一会或者几天之后又出现这个问题，想求助一下 ，感谢作者 **截图** Bug截图.
> 
> 配置信息： 不知道是不是跟机器配置有关系 ![image](https://private-user-images.githubusercontent.com/86301063/326192541-cfed2766-b887-4c1b-8146-23b3d582f790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjgzMTMsIm5iZiI6MTcxNDI2ODAxMywicGF0aCI6Ii84NjMwMTA2My8zMjYxOTI1NDEtY2ZlZDI3NjYtYjg4Ny00YzFiLTgxNDYtMjNiM2Q1ODJmNzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMmExNjhmYTdlNmY0NzNiZjliNjQ1ZTRkMWRhNDFlMjZmYjA3NTNjNjg5ZTkzZWYwMDU1ZjlmYmY0MjkxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJN-dkzt8yn63y7Ri32gT1WAMpYH8eI1oqjexeCoQ9k)
> 
> ![image](https://private-user-images.githubusercontent.com/86301063/326192129-1eb14f7c-52c9-4e4a-8a52-c65b21873e6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjgzMTMsIm5iZiI6MTcxNDI2ODAxMywicGF0aCI6Ii84NjMwMTA2My8zMjYxOTIxMjktMWViMTRmN2MtNTJjOS00ZTRhLThhNTItYzY1YjIxODczZTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMmJjYmE3NzNmNGYzODFkYTk5MGNkZmFhYTQyNjE5NGNkYTY2M2U4MmMzZGNmNzg3OTM2MGQ2YmFmMmM0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.00QQ83CxbDV0RC_U55CnAKhi2m32pE_Mf08TClLRL9Q) ![image](https://private-user-images.githubusercontent.com/86301063/326191985-b693619d-06fd-4f6b-8b43-bcd9bee31d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjgzMTMsIm5iZiI6MTcxNDI2ODAxMywicGF0aCI6Ii84NjMwMTA2My8zMjYxOTE5ODUtYjY5MzYxOWQtMDZmZC00ZjZiLThiNDMtYmNkOWJlZTMxZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MGNkOGU4ZDIxMWFiOWFhMDk1MDA0OWQ2MjVkMmVjMTE3OGM4OTk0MDZlMTcwYzExZjU2NTk4NzE2MTZkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lwRde3Pqp_MGbIMV2gHaW9YzHxLX5d3a4IR7B18wdc0) @FunnyWolf

输入的Lhost不对,应该输入10.10.10.10 而不是10.10.10.10:7788
