### ISSUE TITLE
每次打开viper后，浏览器cpu占用都会变高

### ISSUE THREAD

**Issue by carr0t2** [FunnyWolf/Viper#21]
**描述Bug**
浏览器打开viper后，cpu占用过高（可以确定是viper引起的）

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 输入密码
4. Bug出现了

**截图**
![image](https://user-images.githubusercontent.com/62796978/120807027-18577980-c57a-11eb-857f-3477320e8958.png)

**运行环境:**
viper docker + chrome+ Firefox 

虽然可能没什么影响，但是还是好奇
@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug**
> 浏览器打开viper后，cpu占用过高（可以确定是viper引起的）
> 
> **如何复现**
> 请说明如何复现Bug:
> 
> 1. 安装Viper
> 2. 打开浏览器
> 3. 输入密码
> 4. Bug出现了
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/62796978/120807027-18577980-c57a-11eb-857f-3477320e8958.png)
> 
> **运行环境:**
> viper docker + chrome+ Firefox
> 
> 虽然可能没什么影响，但是还是好奇
> @FunnyWolf

我之前就发现了这个问题,一直以为是只在开发环境存在,但是无法定位到哪个javascript在占用cpu

**Comment by FunnyWolf** [comment]
最近一直在跟踪这个问题,实际测试发现只要访问react写的网站,都有几率触发这个cpu占用的问题,chrome和edge都有,我觉得是react组件与浏览器内核之间的问题
