### ISSUE TITLE
[BUG] 用脚本一键安装后，最新版本缺少redis导致启动失败

### ISSUE THREAD

**Issue by 0day4day** [FunnyWolf/Viper#212]
[BUG] 用脚本一键安装后，最新版本缺少redis导致启动失败，docker logs viper-c报错日志
[ERROR][2024-06-08 07:26:24,038][220] : Error 2 connecting to unix socket: /var/run/redis/redis-server.sock. No such file or directory.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 276, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 277, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 830, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/viper", line 217, in check_redis
    rcon.set('foo', 'bar')
  File "/usr/local/lib/python3.12/dist-packages/redis/commands/core.py", line 2342, in set
    return self.execute_command("SET", *pieces, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/redis/client.py", line 540, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 1104, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 282, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis-server.sock. No such file or directory.
[INFO][2024-06-08 07:26:24,039][443] : [*] redis not start

curl -o f8x https://f8x.io/   # wget -O f8x https://f8x.io/
bash f8x -viper

并且我通过 docker exec -it viper-c bash  进入viper发现  redis目录确实不存在

最新版pull 可能缺少一些文件 镜像  60000也打不开

后面删掉全部镜像目录，手动安装一遍流程  还是缺少redis

经过判断 疑似报错可能最新版redis目录不在

**Comment by FunnyWolf** [comment]
刚安装了一下,没有问题
报错上看不是redis没安装,应该是redis-server没有启动.
具体原因可以看一下/var/log/redis/redis-server.log日志,或者 https://www.yuque.com/vipersec/install/py5fqc 联系我

**Comment by FunnyWolf** [comment]
@0day4day

**Comment by IsR00kie** [comment]
> 刚安装了一下，没有问题 报错上看不是redis没安装，应该是redis-server没有启动。 具体原因可以查看/var/log/redis/redis-server.log日志，或者https://www.yuque.com/vipersec/install/py5fqc联系我

/var/log/redis/redis-server.log 文件不存在 




```
docker-compose up
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
Creating viper-c ... done
Attaching to viper-c
viper-c  | /usr/bin/viper:76: SyntaxWarning: invalid escape sequence '\d'
viper-c  |   result = re.search(r'{}'.format("listen (\d+);"), data)
viper-c  | [INFO][2024-06-17 19:30:32,908][564] : [+] 修改密码完成,新密码为: 
viper-c  | [INFO][2024-06-17 19:30:32,909][426] : [*] 重启redis服务
viper-c  | redis-server: unrecognized service
viper-c  | [ERROR][2024-06-17 19:30:32,914][233] : [Errno 2] No such file or directory
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 229, in check_redis_connect
viper-c  |     client.connect(redis_addr)
viper-c  | FileNotFoundError: [Errno 2] No such file or directory
viper-c  | [INFO][2024-06-17 19:30:32,914][434] : [*] redis is stoped
viper-c  | redis-server: unrecognized service
viper-c  | [ERROR][2024-06-17 19:30:32,918][220] : Error 2 connecting to unix socket: /var/run/redis/redis-server.sock. No such file or directory.
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 276, in connect
viper-c  |     sock = self.retry.call_with_retry(
viper-c  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/retry.py", line 46, in call_with_retry
viper-c  |     return do()
viper-c  |            ^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 277, in <lambda>
viper-c  |     lambda: self._connect(), lambda error: self.disconnect(error)
viper-c  |             ^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 830, in _connect
viper-c  |     sock.connect(self.path)
viper-c  | FileNotFoundError: [Errno 2] No such file or directory
viper-c  |
viper-c  | During handling of the above exception, another exception occurred:
viper-c  |
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 217, in check_redis
viper-c  |     rcon.set('foo', 'bar')
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/commands/core.py", line 2342, in set
viper-c  |     return self.execute_command("SET", *pieces, **options)
viper-c  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/client.py", line 540, in execute_command
viper-c  |     conn = self.connection or pool.get_connection(command_name, **options)
viper-c  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 1104, in get_connection
viper-c  |     connection.connect()
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 282, in connect
viper-c  |     raise ConnectionError(self._error_message(e))
viper-c  | redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis-server.sock. No such file or directory.
viper-c  | [INFO][2024-06-17 19:30:32,920][443] : [*] redis not start
viper-c  | redis-server: unrecognized service
viper-c  | [ERROR][2024-06-17 19:30:35,923][220] : Error 2 connecting to unix socket: /var/run/redis/redis-server.sock. No such file or directory.
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 276, in connect
viper-c  |     sock = self.retry.call_with_retry(
viper-c  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/retry.py", line 46, in call_with_retry
viper-c  |     return do()
viper-c  |            ^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 277, in <lambda>
viper-c  |     lambda: self._connect(), lambda error: self.disconnect(error)
viper-c  |             ^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 830, in _connect
viper-c  |     sock.connect(self.path)
viper-c  | FileNotFoundError: [Errno 2] No such file or directory
viper-c  |
viper-c  | During handling of the above exception, another exception occurred:
viper-c  |
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 217, in check_redis
viper-c  |     rcon.set('foo', 'bar')
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/commands/core.py", line 2342, in set
viper-c  |     return self.execute_command("SET", *pieces, **options)
viper-c  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/client.py", line 540, in execute_command
viper-c  |     conn = self.connection or pool.get_connection(command_name, **options)
viper-c  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 1104, in get_connection
viper-c  |     connection.connect()
viper-c  |   File "/usr/local/lib/python3.12/dist-packages/redis/connection.py", line 282, in connect
viper-c  |     raise ConnectionError(self._error_message(e))
viper-c  | redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis-server.sock. No such file or directory.
viper-c  | [INFO][2024-06-17 19:30:35,924][443] : [*] redis not start
```

**Comment by sssqp** [comment]
一样的问题，请问怎么解决的？
<img width="640" alt="image" src="https://github.com/FunnyWolf/Viper/assets/31802914/d7324367-618f-4353-98ca-64c090ab4d90">

**Comment by FunnyWolf** [comment]
> 一样的问题，请问怎么解决的？ <img alt="image" width="640" src="https://private-user-images.githubusercontent.com/31802914/341210965-d7324367-618f-4353-98ca-64c090ab4d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDc4NDEsIm5iZiI6MTcxODg0NzU0MSwicGF0aCI6Ii8zMTgwMjkxNC8zNDEyMTA5NjUtZDczMjQzNjctNjE4Zi00MzUzLTk4Y2EtNjRjMDkwYWI0ZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAxMzkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNzFjY2ZkNzc3MjY4Y2Q4MjAwNzAyYmUwNDI2OTQxY2NhMWYxMWNkODI4OWVkNTA1YTU2YzQ4MDI2NjczYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bszQlTZ__gGOg17PXXfMgT7uT1nguQMpHPsfr-AkIy4">

无法复现问题,可以手动使用redis-server /etc/redis/redis.conf启动redis
