### ISSUE TITLE
[BUG]kali2024.2安装后msfconsole界面无法显示问题

### ISSUE THREAD

**Issue by chenjinxiang1980** [FunnyWolf/Viper#214]
**复现步骤**
1. 使用fx8自动安装和手动安装后都出现同样问题
2. msfconsole界面为空，已更换火狐和谷歌浏览器进行尝试

**截图**
Bug截图.
![image](https://github.com/FunnyWolf/Viper/assets/107967277/31cb3945-397a-4425-bc33-1d064fbd6718)

@Funnywolf

**Comment by FunnyWolf** [comment]
设置里面看一下msf状态,是不是服务没起来,可以看一下log目录下viper.log日志

**Comment by chenjinxiang1980** [comment]
使用F12查看提示
WebSocket is closed before the connection is established.

![image](https://github.com/FunnyWolf/Viper/assets/107967277/37039f01-19d8-4bd6-b376-78ae41f6301a)

**Comment by chenjinxiang1980** [comment]
服务正常
![image](https://github.com/FunnyWolf/Viper/assets/107967277/21a30d9a-6024-4195-89e2-ab00c412496a)

**Comment by chenjinxiang1980** [comment]
您好，我是盘州市人民医院计算机信息中心陈金祥，您的邮件已经收到。
