### ISSUE TITLE
container error "Connection refused"

### ISSUE THREAD

**Issue by hawaii67** [FunnyWolf/Viper#217]
Since the new version I get an error when starting the container (docker-compose up):

` ConnectionRefusedError: [Errno 111] Connection refused
viper-c  | [INFO][2024-06-28 12:29:13,641][253] : [*] 启动msfrpcd服务
viper-c  | [DEBUG][2024-06-28 12:29:13,642][258] : [Errno 2] No such file or directory: '/root/metasploit-framework/puma.pid'
viper-c  | [ERROR][2024-06-28 12:29:13,702][248] : [Errno 111] Connection refused
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 243, in check_msfrpc
viper-c  |     client.connect((LOCALHOST, msgrpc_port))
`

/root/metasploit-framework/ was not existent - I created it. Same error.

**Comment by nikKrian** [comment]
同样遇到此问题
