### ISSUE TITLE
[BUG]无法启动

### ISSUE THREAD

**Issue by ppofp** [FunnyWolf/Viper#218]
启动nginx服务
[ERROR][2024-07-08 03:28:54,495][248] : [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/bin/viper", line 243, in check_msfrpc
    client.connect((LOCALHOST, msgrpc_port))
ConnectionRefusedError: [Errno 111] Connection refused
[INFO][2024-07-08 03:28:57,496][253] : [*] 启动msfrpcd服务
[DEBUG][2024-07-08 03:28:57,496][258] : [Errno 2] No such file or directory: '/root/metasploit-framework/puma.pid'
[ERROR][2024-07-08 03:28:57,500][248] : [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/bin/viper", line 243, in check_msfrpc
    client.connect((LOCALHOST, msgrpc_port))
ConnectionRefusedError: [Errno 111] Connection refused
[INFO][2024-07-08 03:29:00,501][253] : [*] 启动msfrpcd服务
[DEBUG][2024-07-08 03:29:00,501][258] : [Errno 2] No such file or directory: '/root/metasploit-framework/puma.pid'
[ERROR][2024-07-08 03:29:00,506][248] : [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/bin/viper", line 243, in check_msfrpc
    client.connect((LOCALHOST, msgrpc_port))
ConnectionRefusedError: [Errno 111] Connection refused
[INFO][2024-07-08 03:29:03,507][253] : [*] 启动msfrpcd服务
[DEBUG][2024-07-08 03:29:03,507][258] : [Errno 2] No such file or directory: '/root/metasploit-framework/puma.pid'
[ERROR][2024-07-08 03:29:03,513][248] : [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/bin/viper", line 243, in check_msfrpc
    client.connect((LOCALHOST, msgrpc_port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by ppofp** [comment]
beta版本，修改了result = re.search(r'{}'.format("listen (\d+);"), data)为 result = re.search(r'listen (\d+);', data)  正常启动

**Comment by FunnyWolf** [comment]
> beta版本，修改了result = re.search(r'{}'.format("listen (\d+);"), data)为 result = re.search(r'listen (\d+);', data) 正常启动

感谢反馈,新版本会修复
