### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by zhengjingyuan3855** [FunnyWolf/Viper#22]
最好能把重复的session收录成一个汇总的，实战中看起来比较乱。尤其是网络拓扑，真的不好看
。

**Comment by FunnyWolf** [comment]
> 最好能把重复的session收录成一个汇总的，实战中看起来比较乱。尤其是网络拓扑，真的不好看
> 。

来个图? 或者说有其他工具可以参考吗?

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/viperpython/commit/4c33f58e36b675712748cbfe508b20e0b6b19234

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/6a1afec288e727f1643cc38a738ffb0e65de0901
