### ISSUE TITLE
Problem with loading msf

### ISSUE THREAD

**Issue by hawaii67** [FunnyWolf/Viper#221]
I'm using VIPER for a long time. Really great work.
Well, something has changed, since starting the docker image msf worker status is red.

So the problem is here:
`start-stop-daemon --start --background --quiet --pidfile /root/metasploit-framework/puma.pid --exec /root/.rbenv/shims/puma -- -C /root/metasploit-framework/config/puma_production.rb
`

Where can I configure the paths since they are different on my box:

/root/metasploit-framework/
/root/.rbenv/shims/puma 

Moreover do I have to install puma? Actually I did....but doesn't help

**Comment by FunnyWolf** [comment]
@hawaii67 do not recommend user start msf manual, if msf not status is red, you can try to restart viper container by `docker compose down` `docker compose start`.
if restart is not work, the most likely reason is redis-server is not start (msf rely on redis-server). I suggest install viper on ubuntu22 or kali rolling (In order to use the updated version of the Linux kernel, Docker Compose and Redis Server require)

**Comment by hawaii67** [comment]
Thanks for your reply. I don't start msf manually. I am aware that viper should start it but it doesn't since the paths are not matching for the start-stop-daemon.
I restarted viper many times.
I installed viper on kali rolling.

**Comment by FunnyWolf** [comment]
> Thanks for your reply. I don't start msf manually. I am aware that viper should start it but it doesn't since the paths are not matching for the start-stop-daemon. I restarted viper many times. I installed viper on kali rolling.

make suer you are using latest viper images , it should work if you use kali rolling. you can use `docker exec -it viper-c bash` into docker container. check if msf is running by `ps -ef | grep puma` if puma not runing use `cd /root/metasploit-framework` `thin -c /root/metasploit-framework -l /root/viper/Docker/log/thin.log --rackup /root/metasploit-framework/msf-json-rpc.ru --address 127.0.0.1 --port 60005 --environment production --daemonize --threaded start` to start manual.

**Comment by hawaii67** [comment]
Sorry mate, this doesn't help. I think you are using harcoded paths, like 
/root/metasploit-framework/

On my Kali rolling box it is /usr/share/metasploit-framework/

Just wondering if anybody else has the same issue..............

**Comment by FunnyWolf** [comment]
> Sorry mate, this doesn't help. I think you are using harcoded paths, like /root/metasploit-framework/
> 
> ```
> ps -ef |grep start-stop 
> 
> root      480927  480667 99 14:37 ?        00:00:27 start-stop-daemon --start --background --quiet --pidfile /root/metasploit-framework/puma.pid --exec /root/.rbenv/shims/puma -- -C /root/metasploit-framework/config/puma_production.rb
> ```
> 
> On my Kali rolling box it is /usr/share/metasploit-framework/
> 
> Just wondering if anybody else has the same issue..............

you should not using vipermsf soucecode to run viper

**Comment by hawaii67** [comment]
I do not. I am using docker. This is a bash script I made for updating/starting/stoppiobng VIPER:

`#!/bin/bash




if [ "$#" -eq  "0" ];then
        echo 
        echo 
        echo 
        echo "No arugments supplied"
        echo
        echo
        echo "Usage: VIPER <start|stop|update>"
        echo
        echo
        echo
        echo "Exiting...................."
        echo


elif [ $1  == "update" ];then


	cd /root/VIPER              # Viper installation directory


	# stop and update
	docker compose down         # Delete old container

	rm -f ./db/*
	rm -f ./module/*


	docker compose pull


elif [ $1  == "start" ];then

	# start
	cd /root/VIPER              # Viper installation directory
 	docker compose up -d


elif [ $1  == "stop" ];then
	#stop 
	cd /root/VIPER              # Viper installation directory
	docker compose down         # Delete old container


fi
`

**Comment by FunnyWolf** [comment]
> I do not. I am using docker. This is a bash script I made for updating/starting/stopping VIPER:
> 
> ```
> #!/bin/bash
> 
> if [ "$#" -eq  "0" ];then
>         echo 
>         echo 
>         echo 
>         echo "No arugments supplied"
>         echo
>         echo
>         echo "Usage: VIPER <start|stop|update>"
>         echo
>         echo
>         echo
>         echo "Exiting...................."
>         echo
> 
> 
> elif [ $1  == "update" ];then
> 
> 
> 	cd /root/VIPER              # Viper installation directory
> 
> 
> 	# stop and update
> 	docker compose down         # Delete old container
> 
> 	rm -f ./db/*
> 	rm -f ./module/*
> 
> 
> 	docker compose pull
> 
> 
> elif [ $1  == "start" ];then
> 
> 	# start
> 	cd /root/VIPER              # Viper installation directory
>  	docker compose up -d
> 
> 
> elif [ $1  == "stop" ];then
> 	#stop 
> 	cd /root/VIPER              # Viper installation directory
> 	docker compose down         # Delete old container
> 
> 
> fi
> ```

everything looks good, you have mention /root/metasploit-framework do not exist, after you start docker by `docker compose up -d`, `docker exec -it viper-c bash` `ls /root/metasploit-framework` all vipermsf file should store in this dir

**Comment by hawaii67** [comment]
Ok, we are getting closer. 
Issuing docker exec -it viper-c bash and ls /root/metasploit-framework will show all content - it is there.
I wonder why there is this start-stop.processes on bare kali .......please see the picture.

![grafik](https://github.com/user-attachments/assets/1c7e5261-2b1d-4f19-8b83-8d447401bbaf)

**Comment by hawaii67** [comment]
No, you don't understand. I run no commands outside docker. VIPER is trying to connect to msf but starts puma OUTSIDE of the docker container.

**Comment by hawaii67** [comment]
Can you please check the logs? Here is a connection refused

```
Attaching to viper-c
viper-c  | [INFO][2024-07-29 13:16:42,313][565] : [+] 修改密码完成,新密码为: mypass
viper-c  | [INFO][2024-07-29 13:16:42,314][427] : [*] 重启redis服务
viper-c  | [ERROR][2024-07-29 13:16:43,341][233] : [Errno 2] No such file or directory
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 229, in check_redis_connect
viper-c  |     client.connect(redis_addr)
viper-c  | FileNotFoundError: [Errno 2] No such file or directory
viper-c  | [INFO][2024-07-29 13:16:43,353][435] : [*] redis is stoped
viper-c  | [INFO][2024-07-29 13:16:43,432][441] : [*] redis is started
viper-c  | [INFO][2024-07-29 13:16:43,432][447] : [*] 重启redis完成
viper-c  | [INFO][2024-07-29 13:16:43,435][270] : [+] redis运行中
viper-c  | [INFO][2024-07-29 13:16:43,435][283] : [*] 启动daphne主服务
viper-c  | [INFO][2024-07-29 13:16:43,438][299] : [*] 启动VIPER主服务
viper-c  | [INFO][2024-07-29 13:16:43,455][310] : [*] 启动mitmproxy服务
viper-c  | [INFO][2024-07-29 13:16:43,458][315] : [+] Mitmproxy: http://vpsip:28888
viper-c  | [INFO][2024-07-29 13:16:43,458][316] : [+] root:mypass
viper-c  | [INFO][2024-07-29 13:16:43,461][334] : [*] 启动nginx服务
viper-c  | [ERROR][2024-07-29 13:16:43,528][248] : [Errno 111] Connection refused
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 243, in check_msfrpc
viper-c  |     client.connect((LOCALHOST, msgrpc_port))
viper-c  | ConnectionRefusedError: [Errno 111] Connection refused
viper-c  | [INFO][2024-07-29 13:16:43,530][253] : [*] 启动msfrpcd服务

viper-c  | [ERROR][2024-07-29 13:17:13,555][248] : [Errno 111] Connection refused
viper-c  | Traceback (most recent call last):
viper-c  |   File "/usr/bin/viper", line 243, in check_msfrpc
viper-c  |     client.connect((LOCALHOST, msgrpc_port))
viper-c  | ConnectionRefusedError: [Errno 111] Connection refused
viper-c  | [INFO][2024-07-29 13:17:13,555][253] : [*] 启动msfrpcd服务
viper-c  | [INFO][2024-07-29 13:17:48,957][122] : -------------- 检查服务状态 ----------------
viper-c  | [INFO][2024-07-29 13:17:48,958][123] : 2024-07-29 13:17:48
viper-c  | [INFO][2024-07-29 13:17:48,960][130] : [+] nginx运行中
viper-c  | [INFO][2024-07-29 13:17:48,966][143] : [+] redis运行中
viper-c  | [WARNING][2024-07-29 13:17:48,967][160] : [x] msfrpcd未启动
viper-c  | [INFO][2024-07-29 13:17:48,967][169] : [+] uwsgi运行中


```

**Comment by hawaii67** [comment]
Ok, just to clear, this was my problem:

https://discuss.linuxcontainers.org/t/why-processes-running-inside-the-container-are-visible-outside-the-container-on-host-machine/10832
