### ISSUE TITLE
爱企查cookies配置出现问题

### ISSUE THREAD

**Issue by allinu** [FunnyWolf/Viper#222]
**复现步骤**
https://www.yuque.com/vipersec/help/ary2q9yqzv1zb8k8

**截图**
Bug截图.

`'latin-1' codec can't encode character '\u2026' in position 510: ordinal not in range(256)`

![image](https://github.com/user-attachments/assets/157f20d0-bdb5-429c-84ab-7e9f8f6f4122)

@Funnywolf

**Comment by FunnyWolf** [comment]
> **复现步骤** https://www.yuque.com/vipersec/help/ary2q9yqzv1zb8k8
> 
> **截图** Bug截图.
> 
> `'latin-1' codec can't encode character '\u2026' in position 510: ordinal not in range(256)`
> 
> ![image](https://private-user-images.githubusercontent.com/32992109/352708581-157f20d0-bdb5-429c-84ab-7e9f8f6f4122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjQxMzEsIm5iZiI6MTcyMjIyMzgzMSwicGF0aCI6Ii8zMjk5MjEwOS8zNTI3MDg1ODEtMTU3ZjIwZDAtYmRiNS00MjljLTg0YWItN2U5ZjhmNmY0MTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAzMzAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlM2U2NmZjOTczMjcxYjExYjZmM2FlNDY5YzEyZjg1NmNjNWE5MTE2MGEzZTExZGFkZjdhMjliMTc3ZGFhMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0c1377t5s3xVcOpMWSDFS_7UwH1N2GroSep6USwD1Gk)
> 
> @FunnyWolf

我测试了一下没问题,应该是你在操作时拷贝多了,
![image](https://github.com/user-attachments/assets/9cd2dc96-ff52-42bd-bf33-95f3e09392cb)
