### ISSUE TITLE
[BUG]已重装，但msf仍不能用

### ISSUE THREAD

**Issue by lrxG** [FunnyWolf/Viper#228]
![image](https://github.com/user-attachments/assets/18484538-99c6-4094-8d0f-b88d7902cee7)
![image](https://github.com/user-attachments/assets/c51b6551-6c93-4c3b-a6fd-6c95efdfa291)

**Comment by nikKrian** [comment]
same problem +1

**Comment by hawaii67** [comment]
Same here, but waiting around 15 mins (depending on the power of your system I think) the red MSF indicator (worker status) turns green and it works.

**Comment by FunnyWolf** [comment]
3.0版本已修复
