### ISSUE TITLE
使用reverse_http和reverse_https生成的exe载荷无法使用，程序崩溃导致无法上线

### ISSUE THREAD

**Issue by laohuan12138** [FunnyWolf/Viper#23]
使用这两个paylaod生成的载荷无法上线，调试显示程序已崩溃，只有reverse_tcp能顺利上线。

**Comment by FunnyWolf** [comment]
> 使用这两个paylaod生成的载荷无法上线，调试显示程序已崩溃，只有reverse_tcp能顺利上线。

请反馈一下监听具体的配置信息

**Comment by stuhk** [comment]
我也是同样的问题  win10 x64

**Comment by FunnyWolf** [comment]
> 我也是同样的问题 win10 x64

![image](https://user-images.githubusercontent.com/17685281/121845525-28105400-cd18-11eb-9e10-fb232b956507.png)
使用这种免杀载荷是否能上线?

**Comment by FunnyWolf** [comment]
先关闭,后续复现再打开
