### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by Aziqzz** [FunnyWolf/Viper#24]
有些内网主机出网是通过内部的代理服务器出网的，那么我们生成的木马需要先走内网代理服务器，那么就需要指定代理地址，建议把msf中的HttpProxyHost、HttpProxyPort、HttpProxyUser、HttpProxyPass参数加到自定义参数里面供特殊环境中使用（比如msf payload中windows/x64/meterpreter/reverse_http就有设置这些参数的功能，可以通过show advanced查看）

**Comment by freeAhao** [comment]
何大佬说的对

**Comment by FunnyWolf** [comment]
> 有些内网主机出网是通过内部的代理服务器出网的，那么我们生成的木马需要先走内网代理服务器，那么就需要指定代理地址，建议把msf中的HttpProxyHost、HttpProxyPort、HttpProxyUser、HttpProxyPass参数加到自定义参数里面供特殊环境中使用（比如msf payload中windows/x64/meterpreter/reverse_http就有设置这些参数的功能，可以通过show advanced查看）


在使用windows/x64/meterpreter/reverse_https这种载荷时,会自动调用windows的系统代理尝试连接C2,所以msf在鱼叉攻击外企或者大型企业时比CS好用,因为你不用事先了解对方内网的代理服务器是什么.

**Comment by freeAhao** [comment]
> > 有些内网主机出网是通过内部的代理服务器出网的，那么我们生成的木马需要先走内网代理服务器，那么就需要指定代理地址，建议把msf中的HttpProxyHost、HttpProxyPort、HttpProxyUser、HttpProxyPass参数加到自定义参数里面供特殊环境中使用（比如msf payload中windows/x64/meterpreter/reverse_http就有设置这些参数的功能，可以通过show advanced查看）
> 
> 在使用windows/x64/meterpreter/reverse_https这种载荷时,会自动调用windows的系统代理尝试连接C2,所以msf在鱼叉攻击外企或者大型企业时比CS好用,因为你不用事先了解对方内网的代理服务器是什么.

可以动态获取不同payload的所有参数吗，并动态构建自定义参数列表，而不是硬编码几个固定的参数。

**Comment by FunnyWolf** [comment]
> > > 有些内网主机出网是通过内部的代理服务器出网的，那么我们生成的木马需要先走内网代理服务器，那么就需要指定代理地址，建议把msf中的HttpProxyHost、HttpProxyPort、HttpProxyUser、HttpProxyPass参数加到自定义参数里面供特殊环境中使用（比如msf payload中windows/x64/meterpreter/reverse_http就有设置这些参数的功能，可以通过show advanced查看）
> > 
> > 
> > 在使用windows/x64/meterpreter/reverse_https这种载荷时,会自动调用windows的系统代理尝试连接C2,所以msf在鱼叉攻击外企或者大型企业时比CS好用,因为你不用事先了解对方内网的代理服务器是什么.
> 
> 可以动态获取不同payload的所有参数吗，并动态构建自定义参数列表，而不是硬编码几个固定的参数。

是不是需要在前端UI能动态添加监听的所有参数信息(或者说动态选择),这个功能考虑过添加,但是前端实现起来太麻烦了,所以就没加,其实在msfconsole中建立的监听在UI上也能展示,我加入到TODO里面吧

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/viperjs/commit/f0518ec94aa01df3a44658c89bc74cbf061a837b

**Comment by FunnyWolf** [comment]
权衡了一下,觉得如果把handler的全部参数都放在ui上太乱了,用户也不一定全用上,所以就加了可能有用处的一些参数
