### ISSUE TITLE
模块前序检查失败,检查函数内部错误[BUG]

### ISSUE THREAD

**Issue by heimingdan** [FunnyWolf/Viper#26]
系统服务持久化  提示 模块前序检查失败,检查函数内部错误

**Comment by FunnyWolf** [comment]
同 https://github.com/FunnyWolf/Viper/issues/25 一样,已经通过https://github.com/FunnyWolf/viperpython/commit/8a0c2db16c00ecfa8fd46b18036afb73ccd9d45c解决,下个版本发布.不要重复提issus

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/6a1afec288e727f1643cc38a738ffb0e65de0901
