### ISSUE TITLE
建议优化重复的sessions，提高美观度，让使用者一目了然

### ISSUE THREAD

**Issue by zhengjingyuan3855** [FunnyWolf/Viper#27]
> 
![捕获](https://user-images.githubusercontent.com/55523076/122067295-0d2c0580-ce26-11eb-8d99-3f91bea79757.PNG)最好能把这些重复的sessions合并在一起，让使用者一目了然。

**Comment by ViCrack** [comment]
> 
> 之前有同学提过这个需求,合并重复的session有一个问题解决不了,就是运行模块或者文件浏览的时候需要获取sessionid,如果合并了的话viper没法判断用户想用哪个session进行操作

不妨加一个分组功能 , 如果重复的话合并成一组 , 可以折叠和展开 , 可以按IP/标签/系统等条件切换分组 , 新session创建的时候自动归并到所属组中
界面类似[pull/542](https://github.com/quasar/Quasar/pull/542) 不知道这种是不是能满足要求

**Comment by FunnyWolf** [comment]
> > 之前有同学提过这个需求,合并重复的session有一个问题解决不了,就是运行模块或者文件浏览的时候需要获取sessionid,如果合并了的话viper没法判断用户想用哪个session进行操作
> 
> 不妨加一个分组功能 , 如果重复的话合并成一组 , 可以折叠和展开 , 可以按IP/标签/系统等条件切换分组 , 新session创建的时候自动归并到所属组中
> 界面类似[pull/542](https://github.com/quasar/Quasar/pull/542) 不知道这种是不是能满足要求

后续会调研一下

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/999172586441c1803304619833590c950560bc03
功能已实现
