### ISSUE TITLE
请问viperjs有详细一点的本地开发调试文档吗？

### ISSUE THREAD

**Issue by TesterCC** [FunnyWolf/Viper#28]
您好，请问 https://github.com/FunnyWolf/viperjs 有详细一点的本地开发调试文档吗？
目前viperjs代码拉到本地，直接安装环境后，运行umi dev访问的话是一个空白的页面。

**Comment by FunnyWolf** [comment]
> 您好，请问 https://github.com/FunnyWolf/viperjs 有详细一点的本地开发调试文档吗？
> 目前viperjs代码拉到本地，直接安装环境后，运行umi dev访问的话是一个空白的页面。

当前暂时没有关于viperjs和vipermsf的开发文档,因为本身会react和ruby的人员不多.
这里可以简单说一下如何搭建viperjs的调试环境

先按照https://www.yuque.com/vipersec/code/nqmgvy搭建python的开发环境
注意这里将127.0.0.1改成0.0.0.0,也就是把django服务暴露出来
![image](https://user-images.githubusercontent.com/17685281/122756276-c710ef00-d2c8-11eb-9d94-12b3f441493a.png)

https://github.com/FunnyWolf/viperjs/blob/main/config/config.js
修改
```
target: 'http://127.0.0.1:8002/'
```
为
```
target: 'http://虚拟机ip地址:60002/'
```
就是将js的请求转发到django
然后npm run start:no-mock 就可以了

**Comment by TesterCC** [comment]
@FunnyWolf 十分感谢，我再试试
