### ISSUE TITLE
[BUG]FOFA API 验证失败

### ISSUE THREAD

**Issue by LoneWolf1927** [FunnyWolf/Viper#29]
**描述Bug**
FOFA API 验证无法通过，输入FOFA email and key后，系统提示[输入的FOFA配置不可用,请检查email及key是否正确].

**如何复现**
1. 安装Viper
2. 打开浏览器
3. 进入[平台设置]-->[FOFA API]
4. 输入FOFA email and key[信息确定输入正确]，点击[更新]
5. 系统提示[输入的FOFA配置不可用,请检查email及key是否正确] / 多次尝试均失败

**预期行为**
验证通过.

**截图**
![image](https://user-images.githubusercontent.com/24381168/123045154-2425b580-d42d-11eb-9976-90789d60a914.png)

**运行环境:**
 - OS: [ubuntu18.04]
 - Browser [chrome]
 - Version [92.0.4484.7]

@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug**
> FOFA API 验证无法通过，输入FOFA email and key后，系统提示[输入的FOFA配置不可用,请检查email及key是否正确].
> 
> **如何复现**
> 
> 1. 安装Viper
> 2. 打开浏览器
> 3. 进入[平台设置]-->[FOFA API]
> 4. 输入FOFA email and key[信息确定输入正确]，点击[更新]
> 5. 系统提示[输入的FOFA配置不可用,请检查email及key是否正确] / 多次尝试均失败
> 
> **预期行为**
> 验证通过.
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/24381168/123045154-2425b580-d42d-11eb-9976-90789d60a914.png)
> 
> **运行环境:**
> 
> * OS: [ubuntu18.04]
> * Browser [chrome]
> * Version [92.0.4484.7]
> 
> @FunnyWolf

不好意思,因为我的FOFA账号失效了,所以这个功能现在调试不了~

**Comment by FunnyWolf** [comment]
fofa非会员账号不允许使用rest_api

**Comment by LoneWolf1927** [comment]
我的FOFA账户是VIP，KEY是合适的
