### ISSUE TITLE
[BUG] 无法重置密码

### ISSUE THREAD

**Issue by Richard-Tang** [FunnyWolf/Viper#30]
**描述Bug**

使用以下命令无法进行密码重置！

```bash
docker exec -it viper-c bash
viper -pw diypassword
```

提示错误信息

```bash
Traceback (most recent call last):
  File "/usr/bin/viper", line 389, in <module>
    if action.lower() == "healthcheck":
AttributeError: 'NoneType' object has no attribute 'lower'
```

**截图**

![image](https://user-images.githubusercontent.com/30547741/123621328-ab17cb00-d83d-11eb-9d88-5c1d1f55cdc9.png)

**运行环境:**
 - OS: `CentOS Linux release 7.6.1810 (Core)`
 - Docker: `version 20.10.7, build f0df350`
 - Version: `Viper-v1.3.13 20210627`

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/viperpython/commit/805e75b9c50fc5acd184985825f2ac39de38c795

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/e2a61e885873fd3318d947a2058eb16548f3a734
