### ISSUE TITLE
生成的客户端 无法运行在windwos 2003 上

### ISSUE THREAD

**Issue by hongwei520** [FunnyWolf/Viper#33]
![1625721366(1)](https://user-images.githubusercontent.com/39451921/124866328-d1ccc300-dfee-11eb-8b69-e0bb0847735f.jpg)

**Comment by FunnyWolf** [comment]
该问题在win2003上未复现,
![image](https://user-images.githubusercontent.com/17685281/125156174-b56b8a80-e196-11eb-94a2-03447815e8e2.png)
