### ISSUE TITLE
[BUG] 删除viper的docker数据后并重建后，Viper一直在不断生成监听载荷，无法停止。

### ISSUE THREAD

**Issue by TesterCC** [FunnyWolf/Viper#34]
**描述Bug**
请简短描述遇到的Bug.

**如何复现**
请说明如何复现Bug:
（非必现步骤，只是说明我做的操作）
1. 安装Viper，切换成本地开发的模式
2. 新建了两个 windows/meterpreter/bind_tcp 的监听载荷
3. 然后测试了一些直接上线的自定义exp
4. docker一直保持运行，第二天发现Bug出现了：
Viper一直在不断生成监听载荷，无法停止。

个人尝试删除挂载数据库和docker-compose down ，但是启动后的进入Viper Web界面，监听载荷列表一直在不断创建新的监听载荷（而且是重复的），实时输出也在显示新建监听成功XXX,JobID:XXXX。

**截图**
![](https://cdn.jsdelivr.net/gh/TesterCC/pic_bed2/企业微信截图_16257172351045.png)
![](https://cdn.jsdelivr.net/gh/TesterCC/pic_bed2/企业微信截图_16257172921.png)
![](https://cdn.jsdelivr.net/gh/TesterCC/pic_bed2/企业微信截图_16257182262635.png)

**运行环境:**
 - OS: [Ubuntu 18.04 with Docker]
 - Browser [Chrome]
 - Version  [ Viper v1.3.14]

**补充信息**

希望知道如何停止不断新建监听载荷，因为不停创建监听造成页面卡顿，无法正常调试自定义exp了。

@Funnywolf

**Comment by TesterCC** [comment]
补充一下：后来我把最开始编号1-4的监听载荷给删除了，过了一会儿刷新Viper Web界面终于不再重复继续创建监听了载荷了，根据控制台的文字提示这个时候已经新建了2000+的监听载荷了。

**Comment by FunnyWolf** [comment]
viper的python进程每次启动会把redis缓存中的监听配置读出来,然后调用api在msf中新建,循环建立了2000多个监听应该是viper的python进程不断重启导致的,重启原因可能是本地开发模式的问题,一般来说reverse类型的监听不会出现重复(因为端口被占用了),bind类型监听我没有测试过,可以贴一下viperpython.log内容,看一下为什么python进程一直重启

**Comment by TesterCC** [comment]
> viper的python进程每次启动会把redis缓存中的监听配置读出来,然后调用api在msf中新建,循环建立了2000多个监听应该是viper的python进程不断重启导致的,重启原因可能是本地开发模式的问题,一般来说reverse类型的监听不会出现重复(因为端口被占用了),bind类型监听我没有测试过,可以贴一下viperpython.log内容,看一下为什么python进程一直重启

---

当时还在不断创建新的bind监听时，用tail- f监控过viperpython.log和其它日志，当时并没有什么异常日志。看看以后能不能找到必现场景了。

**Comment by FunnyWolf** [comment]
先关闭这个issus,如果后续问题再次出现再打开.
