### ISSUE TITLE
[BUG] pull 失败

### ISSUE THREAD

**Issue by deaph** [FunnyWolf/Viper#37]
**描述Bug**
pull 报错

**如何复现**
请说明如何复现Bug:
1. 安装Viper

**预期行为**
预期pull成功

**截图**
![image](https://user-images.githubusercontent.com/36835575/127297011-cfded3ce-30f9-40cb-b647-bcdbf67fca01.png)

**运行环境:**
 - OS: [e.g. ubuntu18]
 - Version [e.g. 1.3.2]

**补充信息**
/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer 

supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next 

release.
  from cryptography.hazmat.backends import default_backend
Pulling viper ... error

ERROR: for viper  Get https://registry.cn-shenzhen.aliyuncs.com/v2/: dial tcp 47.107.215.73:443: connect: no route to host
ERROR: Get https://registry.cn-shenzhen.aliyuncs.com/v2/: dial tcp 47.107.215.73:443: connect: no route to host
@Funnywolf

**Comment by FunnyWolf** [comment]
https://www.yuque.com/vipersec/faq/ag9xiv

**Comment by deaph** [comment]
单独请求https://registry.cn-shenzhen.aliyuncs.com/v2/
收到这样的返回，这个镜像资源是不是要登录啊？
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

**Comment by FunnyWolf** [comment]
> 单独请求https://registry.cn-shenzhen.aliyuncs.com/v2/
> 收到这样的返回，这个镜像资源是不是要登录啊？
> {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

viper镜像是公开的,不需要登录,单独访问接口是要登录的
