### ISSUE TITLE
无法回连，监听器不处于工作状态

### ISSUE THREAD

**Issue by wumingzhilian** [FunnyWolf/Viper#38]
麻烦师傅指导
运行环境ubuntu
所有安装一键docker
全端口开放
生成监听器，访问页面不会返回it work

**Comment by FunnyWolf** [comment]
> 麻烦师傅指导
> 运行环境ubuntu
> 所有安装一键docker
> 全端口开放
> 生成监听器，访问页面不会返回it work

访问页面的现象是什么,无法连接吗?使用netstat -anpt能看到监听对应端口吗?

**Comment by wumingzhilian** [comment]
`tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN                                              925736/puma 5.3.2 (
tcp        0      0 172.29.187.221:5666     ip:1050      ESTABLISHED                                         925736/puma 5.3.2 (
tcp        0      0 172.29.187.221:5666    ip :1095      TIME_WAIT                                           -
tcp        0      0 172.29.187.221:5666    ip :1094      TIME_WAIT   `
netstat 可以看到端口
访问页面的情况为默认
not found
![image](https://user-images.githubusercontent.com/69114599/127603889-d18f8b8f-9ef4-4a95-bf68-94f463c63912.png)

**Comment by FunnyWolf** [comment]
![image](https://user-images.githubusercontent.com/17685281/127604127-17c0333c-69ab-4186-878e-b6f675c5774b.png)
![image](https://user-images.githubusercontent.com/17685281/127604190-49b6e8e4-85dc-4921-837f-1d91fb11c9e9.png)

**Comment by wumingzhilian** [comment]
多谢师傅，还有一个问题，我想写一个viper指北，师傅这个可以发布吗？

**Comment by FunnyWolf** [comment]
> 多谢师傅，还有一个问题，我想写一个viper指北，师傅这个可以发布吗？
没有问题,发布后可以提交issus,还可以同步到viper文档中

**Comment by wumingzhilian** [comment]
我想发到FB这种开放平台，师傅有方便的联系方式嘛/邮件

**Comment by FunnyWolf** [comment]
> 我想发到FB这种开放平台，师傅有方便的联系方式嘛/邮件

你直接发就可以啦,发完之后把地址贴到issus中,后续会同步到https://www.yuque.com/vipersec中

**Comment by FunnyWolf** [comment]
> > 我想发到FB这种开放平台，师傅有方便的联系方式嘛/邮件
> 
> 你直接发就可以啦,发完之后把地址贴到issus中,后续会同步到[https://www.yuque.com/vipersec中](https://www.yuque.com/vipersec%E4%B8%AD)

也可以联系weixin: xiaofengzishishui
