### ISSUE TITLE
[BUG]在M1的芯片的MAC好像运行不了,用PD安装了arm版的kali 也是一样

### ISSUE THREAD

**Issue by leiyuch** [FunnyWolf/Viper#39]
在M1的芯片的MAC好像运行不了,用PD安装了arm版的kali 也是一样

**Comment by FunnyWolf** [comment]
> 在M1的芯片的MAC好像运行不了,用PD安装了arm版的kali 也是一样

这个没有适配过,涉及的组件太多了

**Comment by UpDownXH** [comment]
我就说，怎么不行
