### ISSUE TITLE
我自己写了exp，麻烦问下，怎么测试exp模块的正确性，谢谢

### ISSUE THREAD

**Issue by srsec** [FunnyWolf/Viper#4]
我自己写了exp，麻烦问下，怎么测试exp模块的正确性，谢谢

**Comment by FunnyWolf** [comment]
> 我自己写了exp，麻烦问下，怎么测试exp模块的正确性，谢谢

你是说自己写了viper的模块还是msf模块?

**Comment by srsec** [comment]
嗯，是viper模块，怎么实时去调试，脚本的错误。而不是上传一次，看看有没有错误，在去改。谢谢

**Comment by FunnyWolf** [comment]
> 嗯，是viper模块，怎么实时去调试，脚本的错误。而不是上传一次，看看有没有错误，在去改。谢谢

搭建开发环境的比较复杂,具体思路可以使用pycharm的远程调试在docker容器中起调试器,然后本地连接调试器,docker中有viper的后台python代码及魔改后的msf代码,都是明文的,没有加密,具体django的启动信息可以查看viper.py的启动代码.不过这种方式开发体验很不好.

**Comment by srsec** [comment]
好的，谢谢，主要我写了个提权模块，不知道怎么和你viper接口对接起来，丢到module目录下面，也需要去调用参数，比如，ip、payload,这里就没法下手。

**Comment by srsec** [comment]
您有联系方式马？我可以加下马。谢谢

**Comment by FunnyWolf** [comment]
> 好的，谢谢，主要我写了个提权模块，不知道怎么和你viper接口对接起来，丢到module目录下面，也需要去调用参数，比如，一个c段ip、payload,这里就没法下手。

下一个版本会在module的API代码中增加注释及在文档中增加编写模块的手册,当然初版可能会很简陋.
