### ISSUE TITLE
执行 运行信息 时失败

### ISSUE THREAD

**Issue by famei** [FunnyWolf/Viper#41]
**描述Bug**
模块 主机基础信息 的回调函数callhack运行异常

**如何复现**
主机运行信息 点击从新请求时运行失败 提示
模块 主机基础信息 的回调函数callhack运行异常

**截图**
![image](https://user-images.githubusercontent.com/61237921/130594519-052f2d4e-217f-4083-8c7c-47b62e115368.png)

**运行环境:**
 - OS: Windows 10 (10.0 Build 22000).
 - Browser Google Chrome 版本 92.0.4515.159（正式版本） （64 位）
 - Version v1.4.0 20210822

@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug**
> 模块 主机基础信息 的回调函数callhack运行异常
> 
> **如何复现**
> 主机运行信息 点击从新请求时运行失败 提示
> 模块 主机基础信息 的回调函数callhack运行异常
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/61237921/130594519-052f2d4e-217f-4083-8c7c-47b62e115368.png)
> 
> **运行环境:**
> 
> * OS: Windows 10 (10.0 Build 22000).
> * Browser Google Chrome 版本 92.0.4515.159（正式版本） （64 位）
> * Version v1.4.0 20210822
> 
> @FunnyWolf

更新ipaddress库时引入的bug,下个版本修复
