### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nixiabing** [FunnyWolf/Viper#42]
**描述Bug**
Linux主机端口转发和内网路由使用失败

**如何复现**
搭建红日安全 vulnstack3进行测试发现：
攻击机：210.1.10.40（docker部署viper）
双网卡靶机1Linux ： 210.1.55.103 ( 192.168.93.100 )
靶机2Windows：192.168.93.20
已设置端口转发，从内网192.168.93.100的20000端口转发到210.1.55.40的监听端口上，
靶机2也已经成功建立反向shell，与192.168.93.100完成连接，
但平台上仍未看到靶机2上线，请问是何原因？

**预期行为**
请描述预期希望出现的行为.

**截图**
![image](https://user-images.githubusercontent.com/20591728/130921761-49b6f384-10bb-4a1d-a393-2475426caec8.png)
![image](https://user-images.githubusercontent.com/20591728/130921825-46921ee0-40dd-43f6-b68b-7f7654f2c166.png)
![image](https://user-images.githubusercontent.com/20591728/130921843-dd29755f-b4e0-4e1a-9031-88d652644bc1.png)

**补充信息**
如果有需要补充的信息,请在此处描述.
@Funnywolf

**Comment by Nixiabing** [comment]
新建bind_tcp监听，内网路由也加了，靶机2上路由也写了，但好像还是不能上线。。
![image](https://user-images.githubusercontent.com/20591728/131215492-79c8c405-86e6-4645-898b-4ca51a43b8c0.png)
![image](https://user-images.githubusercontent.com/20591728/131215516-c6c445ae-ae28-4e8e-b810-49c166052f66.png)

**Comment by FunnyWolf** [comment]
> 新建bind_tcp监听，内网路由也加了，靶机2上路由也写了，但好像还是不能上线。。
> ![image](https://user-images.githubusercontent.com/20591728/131215492-79c8c405-86e6-4645-898b-4ca51a43b8c0.png)
> ![image](https://user-images.githubusercontent.com/20591728/131215516-c6c445ae-ae28-4e8e-b810-49c166052f66.png)

配的不多,参考如下文档:https://www.yuque.com/vipersec/blog/vcnxah
