### ISSUE TITLE
viper session监控

### ISSUE THREAD

**Issue by Xc1Ym** [FunnyWolf/Viper#43]
在使用钉钉bot的session监控功能时，钉钉bot推送消息可读性差，存在未解码的Unicode字符和utf-8字符，希望可以增强session监控的可读性
![123](https://user-images.githubusercontent.com/29765332/132793305-2fe7eac5-6c96-4d5c-a79d-b118b8485095.png)

**Comment by FunnyWolf** [comment]
> 在使用钉钉bot的session监控功能时，钉钉bot推送消息可读性差，存在未解码的Unicode字符和utf-8字符，希望可以增强session监控的可读性
> ![123](https://user-images.githubusercontent.com/29765332/132793305-2fe7eac5-6c96-4d5c-a79d-b118b8485095.png)

恩,当时只是hack了这个功能,没有优化,接下来版本会针对性优化一下.
