### ISSUE TITLE
[SUGGEST]您好，我的功能标签无法下移

### ISSUE THREAD

**Issue by 9uoer** [FunnyWolf/Viper#44]
当主机上线比较多时，真的不容易看啊
![image](https://user-images.githubusercontent.com/34193964/133752485-de496ffe-8761-402c-a258-2d05288c17b3.png)

**Comment by FunnyWolf** [comment]
> 当主机上线比较多时，真的不容易看啊
> ![image](https://user-images.githubusercontent.com/34193964/133752485-de496ffe-8761-402c-a258-2d05288c17b3.png)

没明白,是主机太多了吗?可以滚动呀

**Comment by 9uoer** [comment]
> > 当主机上线比较多时，真的不容易看啊
> > ![image](https://user-images.githubusercontent.com/34193964/133752485-de496ffe-8761-402c-a258-2d05288c17b3.png)
> 
> 没明白,是主机太多了吗?可以滚动呀

Emmn,是这个意思没错，但总觉得不易于显示，大部分时间我需要看下面的时候都是等后台执行任务，或者一次性操作的时候，加路由等，多少浪费下面大量的空间啊，既然执行命令等也是窗口化，那么能不能做下面的功能页栏可以随意拖动呢？

**Comment by 9uoer** [comment]
我的意思内网代理，加路由没记错也是窗口化

**Comment by FunnyWolf** [comment]
> 我的意思内网代理，加路由没记错也是窗口化

这个是取舍问题,在我实际使用场景中一般就控制10台以下机器,所以上边部分能全显示出来,主要看模块的输出结果.
可能端口扫描会产生大量主机,但是很多就是看一下不会关注.
还有一点是窗口化打开关闭是两次点击,tab是一次点击.
