### ISSUE TITLE
数据库迁移版本化管理

### ISSUE THREAD

**Issue by ViCrack** [FunnyWolf/Viper#47]
发现有时候更新的话 , 数据库结构可能不兼容 , 看文档里面是说要删掉数据库文件重新生成才行 , 我想数据库这部分是否可以搞一个版本化管理的 , 每次升级不兼容的版本能够进行增量更新 , 而不是得手工删掉重来

好像python这边有个SQLAlchemy Alembic等工具可用于数据库迁移 , 不知道有没有比较好的方式处理

![图片](https://user-images.githubusercontent.com/18179821/135722259-7c8260c9-a75f-4b46-9df7-d93ac90484cf.png)

**Comment by FunnyWolf** [comment]
> 发现有时候更新的话 , 数据库结构可能不兼容 , 看文档里面是说要删掉数据库文件重新生成才行 , 我想数据库这部分是否可以搞一个版本化管理的 , 每次升级不兼容的版本能够进行增量更新 , 而不是得手工删掉重来
> 
> 好像python这边有个SQLAlchemy Alembic等工具可用于数据库迁移 , 不知道有没有比较好的方式处理
> 
> ![图片](https://user-images.githubusercontent.com/18179821/135722259-7c8260c9-a75f-4b46-9df7-d93ac90484cf.png)

django有工具可以实现数据库更新,就是实现起来有点费劲,要考虑的情况比较多

**Comment by FunnyWolf** [comment]
> > 发现有时候更新的话 , 数据库结构可能不兼容 , 看文档里面是说要删掉数据库文件重新生成才行 , 我想数据库这部分是否可以搞一个版本化管理的 , 每次升级不兼容的版本能够进行增量更新 , 而不是得手工删掉重来
> > 好像python这边有个SQLAlchemy Alembic等工具可用于数据库迁移 , 不知道有没有比较好的方式处理
> > ![图片](https://user-images.githubusercontent.com/18179821/135722259-7c8260c9-a75f-4b46-9df7-d93ac90484cf.png)
> 
> django有工具可以实现数据库更新,就是实现起来有点费劲,要考虑的情况比较多

viper后续针对数据表结构的更改会很少(至少当前已经28个版本没有改了),数据迁移需要考虑的条件和判断过于复杂,暂时不实现.
