### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by 35465erffd** [FunnyWolf/Viper#5]
为什么不能访问不了ip:60000 
docker ps 查看容器没有打开任何端口
我是严格按照步骤进行的

CONTAINER ID   IMAGE                                                 COMMAND                  CREATED          STATUS          PORTS                     NAMES
63c6fdd2c1be   registry.cn-shenzhen.aliyuncs.com/toys/viper:latest   "viper start -pw leg…"   7 minutes ago    Up 7 minutes                              viper-container

**Comment by FunnyWolf** [comment]
> 为什么不能访问不了ip:60000
> docker ps 查看容器没有打开任何端口
> 我是严格按照步骤进行的
> 
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 63c6fdd2c1be registry.cn-shenzhen.aliyuncs.com/toys/viper:latest "viper start -pw leg…" 7 minutes ago Up 7 minutes viper-container

容器使用的是host network,所以不用导出任何端口,类似直接桥接主机网卡的方式.看日志输出容器已经启动7分钟了,是使用的vps的外网ip:60000访问的吗?或者docker exec -it viper-container bash进入容器,然后netstat -anpt |grep 60000 看nginx起来没

**Comment by 35465erffd** [comment]
ok了 我没有放行端口😂😂😂😂😂😂😂😂😂
