### ISSUE TITLE
安装了证书还是提示没有证书支持，怎么办

### ISSUE THREAD

**Issue by littleheary** [FunnyWolf/Viper#59]
已经生成了新的证书，并且把client.pfx安装在本地了，电脑也重启了，但是访问还是提示。
400 Bad Request
No required SSL certificate was sent
nginx/1.14.0 (Ubuntu)

这个怎么解决？

**Comment by littleheary** [comment]
服务器端是ubuntu，客户端是windows

**Comment by FunnyWolf** [comment]
> 服务器端是ubuntu，客户端是windows

不应该呀,加wx:xiaofengzishishui我看一下

**Comment by hjhjbmy** [comment]
我也遇到了这种情况，vps是CentOS 8.5.2111 x86_64。手动安装和脚本安装都试过了，都无法访问，端口也开启，prx证书也已经导入本机。用curl -k https://127.0.0.1:60000测试的时候显示400 Bad Request No required SSL certificate was sent nginx/1.14.0 (Ubuntu)
