### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by shinegod** [FunnyWolf/Viper#6]
Not Found: /api/auth_routes
msf连接失败,检查 127.0.0.1:60005 是否可用
Not Found: /api/auth_routes
[WARNING][2021-01-18 01:22:13][postmodule][_load_all_modules_config][113][uWSGIWorker1Core0] : 模块加载完成,共加载模块55个 
[WARNING][2021-01-18 01:22:13][msgrpc][start][3349][uWSGIWorker1Core0] : 后台服务启动成功 
[WARNING][2021-01-18 01:22:13][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes 
[pid: 50|app: 0|req: 1/1] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:12 2021] GET /api/auth_routes => generated 179 bytes in 536 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
[WARNING][2021-01-18 01:22:17][msgrpc][call][217][ThreadPoolExecutor-2_3] : msf连接失败,检查 127.0.0.1:60005 是否可用 
[WARNING][2021-01-18 01:22:19][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes 
[pid: 50|app: 0|req: 2/2] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:19 2021] GET /api/auth_routes => generated 179 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)

**Comment by FunnyWolf** [comment]
> Not Found: /api/auth_routes
> msf连接失败,检查 127.0.0.1:60005 是否可用
> Not Found: /api/auth_routes
> [WARNING][2021-01-18 01:22:13][postmodule][_load_all_modules_config][113][uWSGIWorker1Core0] : 模块加载完成,共加载模块55个
> [WARNING][2021-01-18 01:22:13][msgrpc][start][3349][uWSGIWorker1Core0] : 后台服务启动成功
> [WARNING][2021-01-18 01:22:13][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes
> [pid: 50|app: 0|req: 1/1] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:12 2021] GET /api/auth_routes => generated 179 bytes in 536 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
> [WARNING][2021-01-18 01:22:17][msgrpc][call][217][ThreadPoolExecutor-2_3] : msf连接失败,检查 127.0.0.1:60005 是否可用
> [WARNING][2021-01-18 01:22:19][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes
> [pid: 50|app: 0|req: 2/2] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:19 2021] GET /api/auth_routes => generated 179 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)

https://github.com/FunnyWolf/Viper/issues/1 内存问题,可以增加虚拟内存,安装教程中有具体方法

**Comment by shinegod** [comment]
> > 找不到：/ api / auth_routes 
> > msf连接失败，检查127.0.0.1:60005是否可用
> > 找不到：/ api / auth_routes 
> > [警告] [2021-01-18 01:22:13] [postmodule] [_ load_all_modules_config] [113] [uWSGIWorker1Core0]：模块加载完成，共加载模块55个
> > [警告] [2021-01-18 01:22:13] [msgrpc] [开始] [3349] [uWSGIWorker1Core0]：后台服务启动成功
> > [警告] [2021 -01-18 01:22:13] [log] [log_response] [228] [uWSGIWorker1Core0]：找不到：/ api / auth_routes 
> > [pid：50 | app：0 | req：1/1] 0.0.0.0（） {48 vars 753字节} [星期一1月18日01:22:12 2021] GET / api / auth_routes =>生成179字节（536毫秒）（HTTP / 1.1 404）4个报头（128字节）（核心0上有1个开关）
> > [警告] [2021-01-18 01:22:17] [msgrpc] [通话] [217] [ThreadPoolExecutor-2_3]：msf连接失败，检查127.0.0.1:60005是否可用
> > [警告] [2021-01-18 01:22:19] [日志] [日志响应] [228] [uWSGIWorker1Core0]：找不到：/ api / auth_routes 
> > [pid：50 | app：0 | req：2/2] 0.0.0.0（）{48 vars in 753 bytes} [星期一1月18日01:22:19 2021] GET / api / auth_routes =>在1毫秒内生成179字节（HTTP / 1.1 404）128字节中的4个标头（1个开关）在核心0上）
> 
> [＃1](https://github.com/FunnyWolf/Viper/issues/1)内存问题，可以增加虚拟内存，安装教程中有具体方法

4vCPUs | 16GB | c6.xlarge.4
Ubuntu 16.04 server 64bit

**Comment by shinegod** [comment]
> > Not Found: /api/auth_routes
> > msf连接失败,检查 127.0.0.1:60005 是否可用
> > Not Found: /api/auth_routes
> > [WARNING][2021-01-18 01:22:13][postmodule][_load_all_modules_config][113][uWSGIWorker1Core0] : 模块加载完成,共加载模块55个
> > [WARNING][2021-01-18 01:22:13][msgrpc][start][3349][uWSGIWorker1Core0] : 后台服务启动成功
> > [WARNING][2021-01-18 01:22:13][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes
> > [pid: 50|app: 0|req: 1/1] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:12 2021] GET /api/auth_routes => generated 179 bytes in 536 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
> > [WARNING][2021-01-18 01:22:17][msgrpc][call][217][ThreadPoolExecutor-2_3] : msf连接失败,检查 127.0.0.1:60005 是否可用
> > [WARNING][2021-01-18 01:22:19][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes
> > [pid: 50|app: 0|req: 2/2] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:19 2021] GET /api/auth_routes => generated 179 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
> 
> #1 内存问题,可以增加虚拟内存,安装教程中有具体方法

4vCPUs | 16GB | c6.xlarge.4
Ubuntu 16.04 server 64bit

**Comment by FunnyWolf** [comment]
> > > Not Found: /api/auth_routes
> > > msf连接失败,检查 127.0.0.1:60005 是否可用
> > > Not Found: /api/auth_routes
> > > [WARNING][2021-01-18 01:22:13][postmodule][_load_all_modules_config][113][uWSGIWorker1Core0] : 模块加载完成,共加载模块55个
> > > [WARNING][2021-01-18 01:22:13][msgrpc][start][3349][uWSGIWorker1Core0] : 后台服务启动成功
> > > [WARNING][2021-01-18 01:22:13][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes
> > > [pid: 50|app: 0|req: 1/1] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:12 2021] GET /api/auth_routes => generated 179 bytes in 536 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
> > > [WARNING][2021-01-18 01:22:17][msgrpc][call][217][ThreadPoolExecutor-2_3] : msf连接失败,检查 127.0.0.1:60005 是否可用
> > > [WARNING][2021-01-18 01:22:19][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes
> > > [pid: 50|app: 0|req: 2/2] 0.0.0.0 () {48 vars in 753 bytes} [Mon Jan 18 01:22:19 2021] GET /api/auth_routes => generated 179 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
> > 
> > 
> > #1 内存问题,可以增加虚拟内存,安装教程中有具体方法
> 
> 4vCPUs | 16GB | c6.xlarge.4
> Ubuntu 16.04 server 64bit

msf服务没起来，docker内部 (docker exec -it viper-container bash 进入) 执行viper start

**Comment by shinegod** [comment]
> /api/auth_routes

这个一直显示404

**Comment by shinegod** [comment]
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:60000           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:60004         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:60005         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN  

[+] redis运行中
[+] nginx运行中
[+] msfrpcd运行中
[+] VIPER主服务运行中
[+] daphne服务运行中
-------------- 检查服务状态 ----------------
2021-01-18 15:25:40
[+] redis运行中
[+] nginx运行中
[+] msfrpcd运行中
[+] VIPER主服务运行中
[+] daphne服务运行中
[+] 启动完成

[WARNING][2021-01-18 15:24:32][log][log_response][228][uWSGIWorker1Core0] : Not Found: /api/auth_routes

**Comment by shinegod** [comment]
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 15:22 ?        00:00:00 /usr/bin/python3.7 /usr/bin/viper start -pw xxxxx
redis       18     1  0 15:22 ?        00:00:00 /usr/bin/redis-server 127.0.0.1:60004
root        34     1  0 15:22 ?        00:00:00 [nginx] <defunct>
root        38     1  0 15:22 ?        00:00:09 [ruby] <defunct>
root        40     1  0 15:22 ?        00:00:00 [uwsgi] <defunct>
root        41     1  0 15:22 ?        00:00:00 [uwsgi] <defunct>
root        44     1  0 15:22 ?        00:00:00 [sh] <defunct>
root        46     1  0 15:22 ?        00:00:00 [sh] <defunct>
root        47     1  0 15:22 ?        00:00:00 [daphne] <defunct>
root        48     1  0 15:22 ?        00:00:07 [uwsgi] <defunct>
root        83     0  0 15:22 pts/0    00:00:00 bash
root       289     0  0 15:25 pts/1    00:00:00 bash
root      1029    83  0 15:37 pts/0    00:00:00 /usr/bin/python3.7 /usr/bin/viper start
root      1043     0  0 15:37 ?        00:00:00 nginx: master process /usr/sbin/nginx
root      1044  1043  0 15:37 ?        00:00:00 nginx: worker process
root      1045  1043  0 15:37 ?        00:00:00 nginx: worker process
root      1047     0  3 15:37 pts/0    00:00:05 puma 5.1.1 (tcp://127.0.0.1:60005) [viper]
root      1051     0  0 15:37 ?        00:00:00 uwsgi --ini /root/viper/uwsgi.ini
root      1053  1029  0 15:37 pts/0    00:00:00 [sh] <defunct>
root      1055  1029  0 15:37 pts/0    00:00:00 [sh] <defunct>
root      1056     0  0 15:37 pts/0    00:00:00 /usr/bin/python3.7 /usr/local/bin/daphne -u /root/viper/daphne.sock --access-
root      1057  1051  1 15:37 ?        00:00:01 uwsgi --ini /root/viper/uwsgi.ini
root      1228   289  0 15:39 pts/1    00:00:00 ps -ef

**Comment by FunnyWolf** [comment]
> UID PID PPID C STIME TTY TIME CMD
> root 1 0 0 15:22 ? 00:00:00 /usr/bin/python3.7 /usr/bin/viper start -pw xxxxx
> redis 18 1 0 15:22 ? 00:00:00 /usr/bin/redis-server 127.0.0.1:60004
> root 34 1 0 15:22 ? 00:00:00 [nginx]
> root 38 1 0 15:22 ? 00:00:09 [ruby]
> root 40 1 0 15:22 ? 00:00:00 [uwsgi]
> root 41 1 0 15:22 ? 00:00:00 [uwsgi]
> root 44 1 0 15:22 ? 00:00:00 [sh]
> root 46 1 0 15:22 ? 00:00:00 [sh]
> root 47 1 0 15:22 ? 00:00:00 [daphne]
> root 48 1 0 15:22 ? 00:00:07 [uwsgi]
> root 83 0 0 15:22 pts/0 00:00:00 bash
> root 289 0 0 15:25 pts/1 00:00:00 bash
> root 1029 83 0 15:37 pts/0 00:00:00 /usr/bin/python3.7 /usr/bin/viper start
> root 1043 0 0 15:37 ? 00:00:00 nginx: master process /usr/sbin/nginx
> root 1044 1043 0 15:37 ? 00:00:00 nginx: worker process
> root 1045 1043 0 15:37 ? 00:00:00 nginx: worker process
> root 1047 0 3 15:37 pts/0 00:00:05 puma 5.1.1 (tcp://127.0.0.1:60005) [viper]
> root 1051 0 0 15:37 ? 00:00:00 uwsgi --ini /root/viper/uwsgi.ini
> root 1053 1029 0 15:37 pts/0 00:00:00 [sh]
> root 1055 1029 0 15:37 pts/0 00:00:00 [sh]
> root 1056 0 0 15:37 pts/0 00:00:00 /usr/bin/python3.7 /usr/local/bin/daphne -u /root/viper/daphne.sock --access-
> root 1057 1051 1 15:37 ? 00:00:01 uwsgi --ini /root/viper/uwsgi.ini
> root 1228 289 0 15:39 pts/1 00:00:00 ps -ef

Not Found: /api/auth_routes 这个404是前端代码遗留的api,不影响使用,看输出需要的服务应该都起来了,现在使用的话还会报错吗?因为msfrpc启动较慢,可能会在刚启动时出现无法连接问题,30秒后就好了
