### ISSUE TITLE
60000端口拒绝请求

### ISSUE THREAD

**Issue by 2048556128** [FunnyWolf/Viper#60]
按照流程弄完之后，无法访问，是咋回事啊？cd docker-compose up -d后返回
┌──(root💀kali)-[~/VIPER]
└─# docker-compose up -d
viper-c is up-to-date
![Screenshot_2021-10-30-20-08-43-726_com sonelli juicessh](https://user-images.githubusercontent.com/68473229/139532416-bc0640cc-1492-4d66-9e09-c98dfc466627.jpg)

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/51

**Comment by 2048556128** [comment]
> #51

按照流程60000端口没有开启，咋回事啊？

**Comment by FunnyWolf** [comment]
> > #51
> 
> 按照流程60000端口没有开启，咋回事啊？

那是nginx没有起来,什么操作系统装的,是用一键脚本装的还是手工装的
