### ISSUE TITLE
[BUG] v1.5.6

### ISSUE THREAD

**Issue by findexp** [FunnyWolf/Viper#61]
**描述Bug**
1.msfconsole 经常调不出
2.主机界面卡住
3.已经尝试重启docker，问题没有解决
4.重启过docker以后出现历史监听丢失的问题
5.消息那里经常出现：msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用 

**如何复现**
安装的 v1.5.6 版本

附部分日志

> framework.log 
```
[11/01/2021 08:37:18] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 15>
[11/01/2021 08:37:18] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 15>
[11/01/2021 08:37:19] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 15>
[11/01/2021 08:37:21] [e(0)] rex: Failed to find handler for resource: /
```

> viperpython.log
```
内置模块加载完成,加载88个模块
自定义模块加载完成,加载0个模块
后台服务启动成功
Unauthorized: /api/v1/core/currentuser/
Unauthorized: /api/v1/core/currentuser/
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
```

> daphne.log
```
None - - [01/Nov/2021:08:44:25] "WSCONNECTING /ws/v1/websocket/heartbeat/" - -
None - - [01/Nov/2021:08:44:26] "WSDISCONNECT /ws/v1/websocket/heartbeat/" - -
None - - [01/Nov/2021:08:44:26] "WSCONNECTING /ws/v1/websocket/msfconsole/" - -
None - - [01/Nov/2021:08:44:27] "WSCONNECT /ws/v1/websocket/msfconsole/" - -
None - - [01/Nov/2021:08:44:36] "WSCONNECTING /ws/v1/websocket/heartbeat/" - -
None - - [01/Nov/2021:08:44:36] "WSDISCONNECT /ws/v1/websocket/heartbeat/" - -
```

> uwsgi.log
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/viper/./Lib/montior.py", line 147, in sub_heartbeat_thread
    result = HeartBeat.get_heartbeat_result()
  File "/root/viper/./WebSocket/Handle/heartbeat.py", line 86, in get_heartbeat_result
    hosts_sorted, network_data = HeartBeat.list_hostandsession()
  File "/root/viper/./WebSocket/Handle/heartbeat.py", line 184, in list_hostandsession
    sessions = HeartBeat.list_sessions()
  File "/root/viper/./WebSocket/Handle/heartbeat.py", line 444, in list_sessions
    one_session['tunnel_peer_locate_en'] = geoip2_interface.get_geo_str(
  File "/root/viper/./Lib/External/geoip.py", line 47, in get_geo_str
    return " ".join(self.get_geo(ip, lang))
  File "/root/viper/./Lib/External/geoip.py", line 37, in get_geo
    city = response.city.names["en"]
KeyError: 'en'
[pid: 70|app: 0|req: 402/402] 8.8.8.8() {58 vars in 1098 bytes} [Mon Nov  1 08:44:48 2021] GET /api/v1/core/currentuser/ => generated 42 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 210 bytes (1 switches on core 1)
Job "MainMonitor.sub_heartbeat_thread (trigger: interval[0:00:01], next run at: 2021-11-01 08:44:49 UTC)" raised an exception
Traceback (most recent call last):
  File "/root/viper/./Lib/External/geoip.py", line 35, in get_geo
    city = response.city.names[lang]
KeyError: 'en'
```

**截图**
![image](https://user-images.githubusercontent.com/8676062/139646178-c615936e-0131-4a23-8e42-eee6c99470ec.png)

@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug** 1.msfconsole 经常调不出 2.主机界面卡住 3.已经尝试重启docker，问题没有解决 4.重启过docker以后出现历史监听丢失的问题 5.消息那里经常出现：msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
> 
> **如何复现** 安装的 v1.5.6 版本
> 
> 附部分日志
> 
> > framework.log
> 
> ```
> [11/01/2021 08:37:18] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 15>
> [11/01/2021 08:37:18] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 15>
> [11/01/2021 08:37:19] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 15>
> [11/01/2021 08:37:21] [e(0)] rex: Failed to find handler for resource: /
> ```
> 
> > viperpython.log
> 
> ```
> 内置模块加载完成,加载88个模块
> 自定义模块加载完成,加载0个模块
> 后台服务启动成功
> Unauthorized: /api/v1/core/currentuser/
> Unauthorized: /api/v1/core/currentuser/
> msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
> msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
> msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
> msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
> ```
> 
> > daphne.log
> 
> ```
> None - - [01/Nov/2021:08:44:25] "WSCONNECTING /ws/v1/websocket/heartbeat/" - -
> None - - [01/Nov/2021:08:44:26] "WSDISCONNECT /ws/v1/websocket/heartbeat/" - -
> None - - [01/Nov/2021:08:44:26] "WSCONNECTING /ws/v1/websocket/msfconsole/" - -
> None - - [01/Nov/2021:08:44:27] "WSCONNECT /ws/v1/websocket/msfconsole/" - -
> None - - [01/Nov/2021:08:44:36] "WSCONNECTING /ws/v1/websocket/heartbeat/" - -
> None - - [01/Nov/2021:08:44:36] "WSDISCONNECT /ws/v1/websocket/heartbeat/" - -
> ```
> 
> > uwsgi.log
> 
> ```
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
>     retval = job.func(*job.args, **job.kwargs)
>   File "/root/viper/./Lib/montior.py", line 147, in sub_heartbeat_thread
>     result = HeartBeat.get_heartbeat_result()
>   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 86, in get_heartbeat_result
>     hosts_sorted, network_data = HeartBeat.list_hostandsession()
>   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 184, in list_hostandsession
>     sessions = HeartBeat.list_sessions()
>   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 444, in list_sessions
>     one_session['tunnel_peer_locate_en'] = geoip2_interface.get_geo_str(
>   File "/root/viper/./Lib/External/geoip.py", line 47, in get_geo_str
>     return " ".join(self.get_geo(ip, lang))
>   File "/root/viper/./Lib/External/geoip.py", line 37, in get_geo
>     city = response.city.names["en"]
> KeyError: 'en'
> [pid: 70|app: 0|req: 402/402] 8.8.8.8() {58 vars in 1098 bytes} [Mon Nov  1 08:44:48 2021] GET /api/v1/core/currentuser/ => generated 42 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 210 bytes (1 switches on core 1)
> Job "MainMonitor.sub_heartbeat_thread (trigger: interval[0:00:01], next run at: 2021-11-01 08:44:49 UTC)" raised an exception
> Traceback (most recent call last):
>   File "/root/viper/./Lib/External/geoip.py", line 35, in get_geo
>     city = response.city.names[lang]
> KeyError: 'en'
> ```
> 
> **截图** ![image](https://user-images.githubusercontent.com/8676062/139646178-c615936e-0131-4a23-8e42-eee6c99470ec.png)
> 
> @FunnyWolf

这个问题刚刚发现,马上发版本修复

**Comment by FunnyWolf** [comment]
该问题最新版本镜像已修复

**Comment by findexp** [comment]
> 该问题最新版本镜像已修复

刚更新了还是有问题

> uwsgi.log

```
Job "MainMonitor.sub_heartbeat_thread (trigger: interval[0:00:01], next run at: 2021-11-01 13:28:50 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/viper/./Lib/montior.py", line 147, in sub_heartbeat_thread
    result = HeartBeat.get_heartbeat_result()
  File "/root/viper/./WebSocket/Handle/heartbeat.py", line 86, in get_heartbeat_result
    hosts_sorted, network_data = HeartBeat.list_hostandsession()
  File "/root/viper/./WebSocket/Handle/heartbeat.py", line 184, in list_hostandsession
    sessions = HeartBeat.list_sessions()
  File "/root/viper/./WebSocket/Handle/heartbeat.py", line 444, in list_sessions
    one_session['tunnel_peer_locate_en'] = geoip2_interface.get_geo_str(
  File "/root/viper/./Lib/External/geoip.py", line 60, in get_geo_str
    return " ".join(self.get_geo(ip, lang))
TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by FunnyWolf** [comment]
> > 该问题最新版本镜像已修复
> 
> 刚更新了还是有问题
> 
> > uwsgi.log
> 
> ```
> Job "MainMonitor.sub_heartbeat_thread (trigger: interval[0:00:01], next run at: 2021-11-01 13:28:50 UTC)" raised an exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
>     retval = job.func(*job.args, **job.kwargs)
>   File "/root/viper/./Lib/montior.py", line 147, in sub_heartbeat_thread
>     result = HeartBeat.get_heartbeat_result()
>   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 86, in get_heartbeat_result
>     hosts_sorted, network_data = HeartBeat.list_hostandsession()
>   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 184, in list_hostandsession
>     sessions = HeartBeat.list_sessions()
>   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 444, in list_sessions
>     one_session['tunnel_peer_locate_en'] = geoip2_interface.get_geo_str(
>   File "/root/viper/./Lib/External/geoip.py", line 60, in get_geo_str
>     return " ".join(self.get_geo(ip, lang))
> TypeError: sequence item 1: expected str instance, NoneType found
> ```

唉,再修一下吧

**Comment by FunnyWolf** [comment]
> > > 该问题最新版本镜像已修复
> > 
> > 
> > 刚更新了还是有问题
> > > uwsgi.log
> > 
> > 
> > ```
> > Job "MainMonitor.sub_heartbeat_thread (trigger: interval[0:00:01], next run at: 2021-11-01 13:28:50 UTC)" raised an exception
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
> >     retval = job.func(*job.args, **job.kwargs)
> >   File "/root/viper/./Lib/montior.py", line 147, in sub_heartbeat_thread
> >     result = HeartBeat.get_heartbeat_result()
> >   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 86, in get_heartbeat_result
> >     hosts_sorted, network_data = HeartBeat.list_hostandsession()
> >   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 184, in list_hostandsession
> >     sessions = HeartBeat.list_sessions()
> >   File "/root/viper/./WebSocket/Handle/heartbeat.py", line 444, in list_sessions
> >     one_session['tunnel_peer_locate_en'] = geoip2_interface.get_geo_str(
> >   File "/root/viper/./Lib/External/geoip.py", line 60, in get_geo_str
> >     return " ".join(self.get_geo(ip, lang))
> > TypeError: sequence item 1: expected str instance, NoneType found
> > ```
> 
> 唉,再修一下吧

已更新版本,修复此问题
