### ISSUE TITLE
[BUG]session不显示的BUG

### ISSUE THREAD

**Issue by 1n7erface** [FunnyWolf/Viper#62]
在使用VIPER时，启动docker的大概5-10分钟之内运行exe等木马，可以在session列表中显示出来。
但在之后的时间里，运行的木马现实不到web的session列表，无论我刷新页面。但其实session已经上线，此时重启docker容器，然后web会出现session机器。

**Comment by FunnyWolf** [comment]
> 在使用VIPER时，启动docker的大概5-10分钟之内运行exe等木马，可以在session列表中显示出来。 但在之后的时间里，运行的木马现实不到web的session列表，无论我刷新页面。但其实session已经上线，此时重启docker容器，然后web会出现session机器。

这个问题有可能是和 https://github.com/FunnyWolf/Viper/issues/61 是一个问题,获取geo导致handler卡死,建议docker-compose pull 看一下是否是最新镜像.

**Comment by Yang0615777** [comment]
ok,Sir.I'll try it and give a conclusion in the afternoon.

**Comment by Yang0615777** [comment]
尝试最新的版本之后，问题依然存在。还是在docker启动5-10分钟之后不能上线

**Comment by FunnyWolf** [comment]
> 尝试最新的版本之后，问题依然存在。还是在docker启动5-10分钟之后不能上线

发日志看一下?https://www.yuque.com/vipersec/blog/is0ypq

**Comment by Yang0615777** [comment]
看了日志，并没有什么异常。
![image](https://user-images.githubusercontent.com/52184829/140268881-1bcd7f10-90e3-4e50-9db8-bc3df08143a9.png)
但是从右下角可以看出确实有session的上线操作，但是session列表中并无此进程。

**Comment by Yang0615777** [comment]
![image](https://user-images.githubusercontent.com/52184829/140269101-324c7462-d80a-438c-aeb8-664732d09e26.png)
![image](https://user-images.githubusercontent.com/52184829/140269121-e3809683-ea31-4577-a50d-8604a9484bf8.png)
但是我重启docker之后，session列表中会出现此进程。

**Comment by FunnyWolf** [comment]
msfconsole里面有session没?

**Comment by Yang0615777** [comment]
并没有，但是重启之后，msfconsole里面也就有了。

**Comment by Yang0615777** [comment]
我觉得应该是客户端木马运行时，viper收到请求却拒绝连接或连接失败。但是客户端的木马仍在运行状态，当我重启viper时，客户端上线。所以viper应该是监听出问题了在运行长时间之后。

**Comment by Yang0615777** [comment]
如果需要日志截图，请说明哪个日志文件我将附上截图。但是我查看并无异常

**Comment by FunnyWolf** [comment]
> 如果需要日志截图，请说明哪个日志文件我将附上截图。但是我查看并无异常

嗯,问题可能出在监听防火墙这个新功能上,我测试一下

**Comment by Yang0615777** [comment]
我并不这样认为，因为监听防火墙是你让我更新之后最新的版本出现的此功能。但是在更新前此问题就已经存在。方便在VX上聊吗，如果你不便提供你的VX，我的VX是：SecDev_Yang

**Comment by FunnyWolf** [comment]
从日志上来看是ruby申请内存失败导致的session创建失败,但是为什么在系统内存充裕的情况下ruby还会出现申请内存失败问题还需要继续分析一下.

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/16a24a52e0fabaaff410d1a2f5d22e991ea3a37f
