### ISSUE TITLE
[BUG] v1.5.6 删除监听器，服务器仍存在端口占用的问题

### ISSUE THREAD

**Issue by findexp** [FunnyWolf/Viper#63]
**描述Bug**
版本 v1.5.6 ，有会话情况下，删除监听器以后，服务器仍存在端口占用的问题

**如何复现**
1. 新建一个监听，比如80端口
2. 使用该荷载上线一个session会话
3. 删除该监听器
4. Bug出现了，服务器上80端口仍然会被占用
理论上删除监听器，应该所有session会话都掉线的，但是这里却没有
会话没有掉线，端口也还是仍然占用状态

**截图**
```
netstat -antp 

tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      17499/puma 5.5.2
```

@Funnywolf

**Comment by FunnyWolf** [comment]
这个是http类型监听吧?特意这么设计的,如果http监听直接删除session就掉线了,你可以试试吧监听对应的session删除,这时监听就自动退出了.

**Comment by findexp** [comment]
> 这个是http类型监听吧?特意这么设计的,如果http监听直接删除session就掉线了,你可以试试吧监听对应的session删除,这时监听就自动退出了.

是https的监听
不可能删除session啊
1.session如果是注入正常系统进程的，确定删除session进程或者系统不会崩？
2.有时候服务器要用80端口，这里只能选择关闭docker了。所以这个可能不合理
