### ISSUE TITLE
[BUG] v1.5.6 x86的荷载没法调用 mimikatz

### ISSUE THREAD

**Issue by findexp** [FunnyWolf/Viper#64]
**描述Bug**
v1.5.6版本
 x86的荷载没法调用 mimikatz那些

**如何复现**
1. 使用x86荷载上线一个管理权限以上session
2. 调用mimikatz，获取Windows内存密码

**截图**
```
获取Windows内存密码 192.168.1.1
模块执行失败
x64 platform requires x64 meterpreter and mimikatz extension
```

@Funnywolf

**Comment by FunnyWolf** [comment]
这个是mimikatz本身的限制,在x64的机器上如果需要使用
mimikatz必须使用x64的session

**Comment by findexp** [comment]
> 这个是mimikatz本身的限制,在x64的机器上如果需要使用 mimikatz必须使用x64的session

mimikatz好像有x86的吧
