### ISSUE TITLE
[BUG] v1.5.7

### ISSUE THREAD

**Issue by findexp** [FunnyWolf/Viper#65]
**描述Bug**
更新后msf起不来

**如何复现**
请说明如何复现Bug:
1. docker pull 更新了一下
2. 后台msf起不来了。。

**部分日志**
```
[11/13/2021 04:13:39] [d(0)] core: Updated user based module store
[11/13/2021 04:13:44] [e(0)] core: Failed to connect to the database: No database YAML file
[11/13/2021 04:13:47] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 20>
```
我咋是 v1.5.7版本了。。。git这不是1.5.6么。。
@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug** 更新后msf起不来
> 
> **如何复现** 请说明如何复现Bug:
> 
> 1. docker pull 更新了一下
> 2. 后台msf起不来了。。
> 
> **部分日志**
> 
> ```
> [11/13/2021 04:13:39] [d(0)] core: Updated user based module store
> [11/13/2021 04:13:44] [e(0)] core: Failed to connect to the database: No database YAML file
> [11/13/2021 04:13:47] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 20>
> ```
> 
> 我咋是 v1.5.7版本了。。。git这不是1.5.6么。。 @FunnyWolf

1.5.7没写readme,起不来了吗?设置里面渗透服务状态是啥?

**Comment by findexp** [comment]
> > **描述Bug** 更新后msf起不来
> > **如何复现** 请说明如何复现Bug:
> > 
> > 1. docker pull 更新了一下
> > 2. 后台msf起不来了。。
> > 
> > **部分日志**
> > ```
> > [11/13/2021 04:13:39] [d(0)] core: Updated user based module store
> > [11/13/2021 04:13:44] [e(0)] core: Failed to connect to the database: No database YAML file
> > [11/13/2021 04:13:47] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 20>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我咋是 v1.5.7版本了。。。git这不是1.5.6么。。 @FunnyWolf
> 
> 1.5.7没写readme,起不来了吗?设置里面渗透服务状态是啥?

是正常状态，msf起不来，主页面session那里也点不开

**Comment by FunnyWolf** [comment]
uwsgi.log日志发一下

**Comment by findexp** [comment]
> uwsgi.log日志发一下

```
spawned uWSGI master process (pid: 57)
spawned uWSGI worker 1 (pid: 70, cores: 4)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55a41e894e30 pid: 70 (default app)
[WARNING][2021-11-13 19:05:16][rpcclient][call][47][uWSGIWorker1Core0] : msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
[WARNING][2021-11-13 19:05:16][servicestatus][update_service_status][37][uWSGIWorker1Core0] : json_rpc服务无法连接,请确认!
[WARNING][2021-11-13 19:05:19][rpcclient][call][47][uWSGIWorker1Core0] : msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
[WARNING][2021-11-13 19:05:19][servicestatus][update_service_status][37][uWSGIWorker1Core0] : json_rpc服务无法连接,请确认!
[WARNING][2021-11-13 19:05:22][rpcclient][call][47][uWSGIWorker1Core0] : msf连接失败,检查 http://127.0.0.1:60005/api/v1/json-rpc 是否可用
[WARNING][2021-11-13 19:05:22][servicestatus][update_service_status][37][uWSGIWorker1Core0] : json_rpc服务无法连接,请确认!
[WARNING][2021-11-13 19:05:28][postmoduleconfig][load_all_modules_config][215][uWSGIWorker1Core0] : 内置模块加载完成,加载89个模块
[WARNING][2021-11-13 19:05:28][postmoduleconfig][load_all_modules_config][282][uWSGIWorker1Core0] : 自定义模块加载完成,加载0个模块
[WARNING][2021-11-13 19:05:28][montior][start][114][uWSGIWorker1Core0] : 后台服务启动成功
[WARNING][2021-11-13 19:05:28][log][log_response][224][uWSGIWorker1Core0] : Unauthorized: /api/v1/core/currentuser/
[WARNING][2021-11-13 19:05:28][log][log_response][224][uWSGIWorker1Core2] : Unauthorized: /api/v1/core/currentuser/
Sat Nov 13 19:05:28 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
```

**Comment by FunnyWolf** [comment]
这个可能和https://github.com/FunnyWolf/Viper/issues/62相关,尚在定位中

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/16a24a52e0fabaaff410d1a2f5d22e991ea3a37f
