### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [FunnyWolf/Viper#66]
萌新刚写了一篇关于使用cloudflare argo隧道隐藏viper服务器地址
https://tokisaki.top/blog/viper-via-cloudflare-argo/
大佬能不能考虑一下加到文档里的反溯源配置里？

**Comment by FunnyWolf** [comment]
> 萌新刚写了一篇关于使用cloudflare argo隧道隐藏viper服务器地址 https://tokisaki.top/blog/viper-via-cloudflare-argo/ 大佬能不能考虑一下加到文档里的反溯源配置里？

没问题,这个是加在https://www.yuque.com/vipersec/help/xbz4hx中还是在github的readme中单独加一项友情链接?

**Comment by FunnyWolf** [comment]
> 萌新刚写了一篇关于使用cloudflare argo隧道隐藏viper服务器地址 https://tokisaki.top/blog/viper-via-cloudflare-argo/ 大佬能不能考虑一下加到文档里的反溯源配置里？

这个配置方法能不能用于上线session呢?比如reverse_http的payload?

**Comment by Tokisaki-Galaxy** [comment]
加个友情链接吧。

理论上可以，我过几天再写一篇通过Argo上线http/https的。
如果session、后台全部走argo，那么就不用部署在拥有公网IP的VPS上了，甚至可以部署在家里的树莓派上。

**Comment by FunnyWolf** [comment]
> 加个友情链接吧。
> 
> 理论上可以，我过几天再写一篇通过Argo上线http/https的。 如果session、后台全部走argo，那么就不用部署在拥有公网IP的VPS上了，甚至可以部署在家里的树莓派上。

没问题，我明天加上，期待后续文章

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/807e1305e3973e1bce344a0b71cb951e07c1f0e9
