### ISSUE TITLE
[BUG]无法使用https监听载荷

### ISSUE THREAD

**Issue by 9uoer** [FunnyWolf/Viper#67]
**描述Bug**
当使用https监听载荷，且启用ssl证书的时候，无法监听

**截图**
![ssl证书问题](https://user-images.githubusercontent.com/34193964/141794291-ea4336b4-a408-47a1-bf43-a75d1b02323b.png)
![ssl2](https://user-images.githubusercontent.com/34193964/141794303-226970ea-c8a5-4ef1-84ff-d6e1a273e4b8.png)

@Funnywolf

**Comment by FunnyWolf** [comment]
![image](https://user-images.githubusercontent.com/17685281/141869729-0ca0fc1b-7630-4694-b2a9-60079060003a.png)

www.example.com.pem是不是已经被删除了

**Comment by evi1hack** [comment]
+1

![微信截图_20211116142918](https://user-images.githubusercontent.com/16398717/141933413-02775618-028b-424f-a8e3-df3ca0be4dc0.png)

![微信截图_20211116143009](https://user-images.githubusercontent.com/16398717/141933481-fb1d20fa-5588-4dea-b7b9-2cbb21b76f20.png)
![微信截图_20211116142949](https://user-images.githubusercontent.com/16398717/141933502-856c9e5b-6e8c-49fc-8899-01c4388c4c3b.png)

pem没有被删除，试了不行啊。

**Comment by 9uoer** [comment]
对的，没被删除，我也尝试过自己制作pem文件，确实不行。重装镜像之后，纯净系统下安装viper，功能还是不可以使用

**Comment by FunnyWolf** [comment]
> 对的，没被删除，我也尝试过自己制作pem文件，确实不行。重装镜像之后，纯净系统下安装viper，功能还是不可以使用

反馈一下framework.log日志信息吧,看一下具体错误是什么

**Comment by FunnyWolf** [comment]
我已经重现并定位到问题的原因,今天2021-11-16晚上会更新一版,修复这个问题

**Comment by 9uoer** [comment]
> 今天2021-11-16晚上

大佬牛批，刚才不在

**Comment by FunnyWolf** [comment]
新版本已修复
