### ISSUE TITLE
您好作者装完了之后黑屏是什么情况nginx已经启动了。看不到登录框，在vps安装的。

### ISSUE THREAD

**Issue by lfqevf4** [FunnyWolf/Viper#7]
`Failed to load resource: the server responded with a status of 404 (Not Found)
p__Core__HostAndSession.js:1 HostAndSession
umi.js:1 TypeError: Cannot read property '_store' of undefined
    at i (umi.js:1)
    at qa (p__Core__HostAndSession.js:1)
    at pa (umi.js:1)
    at Fu (umi.js:1)
    at Uc (umi.js:1)
    at Fc (umi.js:1)
    at Pc (umi.js:1)
    at umi.js:1
    at t.unstable_runWithPriority (umi.js:1)
    at ui (umi.js:1)`
报错了，这个是什么情况呢？

**Comment by FunnyWolf** [comment]
> `Failed to load resource: the server responded with a status of 404 (Not Found) p__Core__HostAndSession.js:1 HostAndSession umi.js:1 TypeError: Cannot read property '_store' of undefined at i (umi.js:1) at qa (p__Core__HostAndSession.js:1) at pa (umi.js:1) at Fu (umi.js:1) at Uc (umi.js:1) at Fc (umi.js:1) at Pc (umi.js:1) at umi.js:1 at t.unstable_runWithPriority (umi.js:1) at ui (umi.js:1)`
> 报错了，这个是什么情况呢？

看日志是前端umi报错了,这个从来没有遇到过,尝试清理一下浏览器缓存呢,如果解决不了可以发一下chrome的console日志看一下

**Comment by lfqevf4** [comment]
![捕获](https://user-images.githubusercontent.com/77491142/104995381-3015e180-5a61-11eb-9932-3aebaf273a0c.PNG)
这个是chrome的console日志

**Comment by FunnyWolf** [comment]
> ![捕获](https://user-images.githubusercontent.com/77491142/104995381-3015e180-5a61-11eb-9932-3aebaf273a0c.PNG)
> 这个是chrome的console日志

https://github.com/umijs/umi/issues/5479 应该是umi和dva冲突了,是前端框架的问题,理论上不应该影响展示,页面全黑还是一直loading?

**Comment by Lan1-Lan** [comment]
> > ![捕获](https://user-images.githubusercontent.com/77491142/104995381-3015e180-5a61-11eb-9932-3aebaf273a0c.PNG)
> > 这个是chrome的console日志
> 
> [umijs/umi#5479](https://github.com/umijs/umi/issues/5479) 应该是umi和dva冲突了,是前端框架的问题,理论上不应该影响展示,页面全黑还是一直loading?

全黑

**Comment by 35465erffd** [comment]
我也是全黑

**Comment by FunnyWolf** [comment]
> > > ![捕获](https://user-images.githubusercontent.com/77491142/104995381-3015e180-5a61-11eb-9932-3aebaf273a0c.PNG)
> > > 这个是chrome的console日志
> > 
> > 
> > [umijs/umi#5479](https://github.com/umijs/umi/issues/5479) 应该是umi和dva冲突了,是前端框架的问题,理论上不应该影响展示,页面全黑还是一直loading?
> 
> 全黑



> > > ![捕获](https://user-images.githubusercontent.com/77491142/104995381-3015e180-5a61-11eb-9932-3aebaf273a0c.PNG)
> > > 这个是chrome的console日志
> > 
> > 
> > [umijs/umi#5479](https://github.com/umijs/umi/issues/5479) 应该是umi和dva冲突了,是前端框架的问题,理论上不应该影响展示,页面全黑还是一直loading?
> 
> 全黑

已经重现这个bug,但具体原因还没有定位出来,可以通过先访问https://VPSip:60000/#/user/login 来进行登录,暂时规避这个bug

**Comment by FunnyWolf** [comment]
> 我也是全黑

已经重现这个bug,但具体原因还没有定位出来,可以通过先访问https://VPSip:60000/#/user/login 来进行登录,暂时规避这个bug

**Comment by Lan1-Lan** [comment]
![image](https://user-images.githubusercontent.com/20243850/105175467-eca19d00-5b5e-11eb-8c6c-d1fb9b601a1e.png)

**Comment by Lan1-Lan** [comment]
> > 我也是全黑
> 
> 已经重现这个bug,但具体原因还没有定位出来,可以通过先访问https://VPSip:60000/#/user/login 来进行登录,暂时规避这个bug

![image](https://user-images.githubusercontent.com/20243850/105175616-2c688480-5b5f-11eb-9a2f-336821d5b5e0.png)

**Comment by FunnyWolf** [comment]
> > > 我也是全黑
> > 
> > 
> > 已经重现这个bug,但具体原因还没有定位出来,可以通过先访问https://VPSip:60000/#/user/login 来进行登录,暂时规避这个bug
> 
> ![image](https://user-images.githubusercontent.com/20243850/105175616-2c688480-5b5f-11eb-9a2f-336821d5b5e0.png)

端口占用了吗?也可能是msfrpc没起来
![image](https://user-images.githubusercontent.com/17685281/105176051-abf65380-5b5f-11eb-83ed-822e5989d2f4.png)

**Comment by 35465erffd** [comment]
终于弄好了  能登录进来就可以
提个建议 自定义后台地址 登录端口 （参考宝塔）有效防止反渗透
![捕获](https://user-images.githubusercontent.com/77112204/105212937-06f07080-5b89-11eb-99b7-4e4796dba0d6.PNG)

**Comment by FunnyWolf** [comment]
> 终于弄好了 能登录进来就可以
> 提个建议 自定义后台地址 登录端口 （参考宝塔）有效防止反渗透
> ![捕获](https://user-images.githubusercontent.com/77112204/105212937-06f07080-5b89-11eb-99b7-4e4796dba0d6.PNG)

好建议，自定义端口一是用的人容易忘了，二是没法防御全端口扫描，一直没有好的方案

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/dc0991ff504773cc067737684617b0e1458bebfe

**Comment by ViCrack** [comment]
>  自定义后台地址 登录端口

 可选的自定义后台网页地址和端口功能, 用的人可以记录到书签上, 不然这样登录接口也没验证码还是容易被爆破
