### ISSUE TITLE
[BUG]新建监听LHOST似乎有部分域名无法设置

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [FunnyWolf/Viper#70]
**描述Bug**
请简短描述遇到的Bug.
新建监听中，LHOST参数似乎有部分域名无法设置。。。

**如何复现**
请说明如何复现Bug:
1. 新建监听
2. 设置LHOST为某个域名
3. 提示新建监听超时
4. Bug出现了

输出里的错误提示：
MSFRPC> Application server error: One or more options failed to validate: LHOST.

**截图**
因为在新建监听中可能无法准确体现问题，所以截了msfconsole里面的
请提供Bug出现时的截图.
![1](https://user-images.githubusercontent.com/61621971/142730220-3670626d-f134-4dbd-8090-a6b068fbd140.jpg)

![2](https://user-images.githubusercontent.com/61621971/142729647-740bd038-70bc-4d96-846f-ad69b1dccc15.jpg)

在官方的msfconosle中可以正常设置域名
![3](https://user-images.githubusercontent.com/61621971/142729618-e8f26e1c-a663-4a1d-8c31-098fabdf5823.jpg)

@Funnywolf

**Comment by FunnyWolf** [comment]
设置lhost时代码有一处检查
```
      begin
        getaddr_result = ::Rex::Socket.getaddress(value, true)
        # Covers a wierdcase where an incomplete ipv4 address will have it's
        # missing octets filled in  with 0's. (e.g 192.168 become 192.0.0.168)
        # which does not feel like a legit behaviour
        if value =~ /^\d{1,3}(\.\d{1,3}){1,3}$/
          return false unless value =~ Rex::Socket::MATCH_IPV4
        end
      rescue
        return false
      end
```
 ::Rex::Socket.getaddress表示设置的域名必须有dns记录才可以.

viper中和原生msfconsole的结果不同是可能是以下原因:
viper的docker中无法解析tp.astraia.top,原生msfconsole操作系统可以解析tp.astraia.top这个域名
另外我在可以联网的viper环境测试了一下,可以讲lhost设置成tp.astraia.top

**Comment by Tokisaki-Galaxy** [comment]
似乎是我自己服务器dns设置有问题，无法解析到C2地址。
更换DNS地址后解决了，抱歉。
