### ISSUE TITLE
[BUG] 前端 控制台session无法加载

### ISSUE THREAD

**Issue by GSCSDSUN** [FunnyWolf/Viper#71]
**描述Bug**
使用一段时间后 控制台session无法加载 不确定BUG如何触发 

**如何复现**

请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 输入密码
4. Bug出现了

**截图**
请提供Bug出现时的截图.
![E(DOV8BG (`7J8K T)GHP%W](https://user-images.githubusercontent.com/46085443/142750124-97ad7fc6-1134-4800-9c19-4503d2aef09e.png)
@Funnywolf

**Comment by GSCSDSUN** [comment]
还有 使用一段时间之后 msfrpcd 会死 重启也无法解决 只能等着

**Comment by GSCSDSUN** [comment]
但是只要删除redis的 数据就能恢复了

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/62

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/69

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/viperpython/commit/5629d5783a4c4a1a5a34bad36a6ecc707498f092

**Comment by sbhack** [comment]
使用一段时间之后 msfrpcd 会死 重启也无法解决 只能等着  这个问题确实有，我这边也遇到了

**Comment by lapalipi** [comment]
emmm....同遇+1
这就很蛋疼了。

**Comment by AdminPoker** [comment]
同遇，我之前开启了防火墙会出现这个问题，但是我现在把所有防火墙全部关闭了，还是出现了这个问题
<img width="1790" alt="图片" src="https://user-images.githubusercontent.com/51812136/144543321-8c936538-eb6f-4d94-a586-5073a0c7585f.png">

**Comment by AdminPoker** [comment]
我这边也出现了这个问题，之前我把iptables开起来会出现这个问题，但是现在我已经把iptbales已经关闭了，还是出现了这个问题
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/51812136/144543474-e44c8ca3-a551-40ce-9b3e-20b415249d3b.png">
防火墙开启后，websocks就不能通信了，通过报错，好像是跨域问题，能不能后端把跨域这个加个cors头解决下

**Comment by FunnyWolf** [comment]
> 

websocket没有使用cookie认证,502应该是网络问题,刷新页面无法恢复?

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/16a24a52e0fabaaff410d1a2f5d22e991ea3a37f
