### ISSUE TITLE
msf http使用cloudflare argo上线

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [FunnyWolf/Viper#72]
https://tokisaki.top/blog/meterpreter-via-cloudflare-argo/
msf http使用cloudflare argo上线，隐藏C2真实地址。

下一步想解决https，但是没啥思路，不知道证书是用哪一个。百度了一圈也没找到啥相关的，不知道大佬有没有啥想法。

**Comment by FunnyWolf** [comment]
https://tokisaki.top/blog/viper-via-cloudflare-argo/ 这个初始教程是不是多配点图?看了一遍没会配

**Comment by FunnyWolf** [comment]
> https://tokisaki.top/blog/meterpreter-via-cloudflare-argo/ msf http使用cloudflare argo上线，隐藏C2真实地址。
> 
> 下一步想解决https，但是没啥思路，不知道证书是用哪一个。百度了一圈也没找到啥相关的，不知道大佬有没有啥想法。

argo默认支持https(比如https://vip.test.com和http://vip.test.com都能访问到viper后台)
所以viper中启动一个http监听,但是生成一个同样配置的https载荷(证书用argo生成的pem证书),默认是可以上线的,

**Comment by Tokisaki-Galaxy** [comment]
谢谢大佬，由于我是高中生，要周末才能回家弄，其余时间只能在学校呆着。我下周末回家试试。
另外那个教程我没有注意，回去我会多配点图的。

**Comment by Tokisaki-Galaxy** [comment]
另外想问问，argo上线之后由于是端口转发，所以VIPER里显示的IP地址是127.0.0.1 。
有没有有可能通过某种端口来获得外网IP地址，并同步（修改）VIPER里面的IP地址。

**Comment by FunnyWolf** [comment]
> 

上线后viper的`获取互联网出口IP`模块可以获取到已控主机的外网IP,viper里面的ip地址当前无法修改,不过session是支持添加备注的,可以把ip地址写在备注里面,也算一个方法

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/48fa570038e0cb8face649a3bf5c7f42ce5993c9
