### ISSUE TITLE
全网扫描数据能不能支持自定义导入

### ISSUE THREAD

**Issue by evi1hack** [FunnyWolf/Viper#74]
全网扫描数据能不能支持自定义导入：
![image](https://user-images.githubusercontent.com/16398717/143539046-e0841aa2-1467-41fd-ac8b-4cc379a355f6.png)
现在的情况是只能从空间搜索引擎搜索导入，假如我已经有一批验证过的IP ，想放到全网扫描这里来利用里面的模块，能否支持自定义导入数据。

感谢大佬。

**Comment by FunnyWolf** [comment]
> 

这个idea非常赞,我争取下个版本就实现这个功能

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/bd370f0278dc07bcdd092ff51b7d9ce46eb45270
