### ISSUE TITLE
Not all Modules are included in v1.5.8  [BUG]

### ISSUE THREAD

**Issue by redblueteam** [FunnyWolf/Viper#75]
**描述Bug**
I am very new to using this awesome framework tool.

I read the modules' readme under (https://www.yuque.com/vipersec/module/taxm8t) and I found some of the modules are missing, e.g. Office宏钓鱼文档

![image](https://user-images.githubusercontent.com/29709246/143687027-e7638efb-cbcc-4454-91b6-8412b99e5831.png)

Is this a bug or intentionally hiding? Thanks.

**如何复现**
1. Install viper by using F8X script
2. There is no module under "Automation -> Initial Access"

![image](https://user-images.githubusercontent.com/29709246/143687100-6de111ca-4926-4eb5-a54b-a5e1ff9155f3.png)

Thanks.

**截图**
Provided in the above description. Thanks.

@Funnywolf

**Comment by evi1hack** [comment]
First of all, you need to get a usable session (that is, the target has run your Trojan file online successfully), and on the basis of this available session, you can use these attack modules. I don't see a session available on your screenshot. You can refer to the tutorial here: https://www.yuque.com/viper-en/inh85g/gyvkrq

**Comment by redblueteam** [comment]
Thanks for your prompt response. I am a little bit confused here, cause I am thinking the function under "Initial Access" literally should not require an existing session, as I suppose it is used to generate some useful phishing files (e.g.a phishing doc) for sending to the target to obtain a session (if the target opens the phishing doc).

> First of all, you need to get a usable session (that is, the target has run your Trojan file online successfully), and on the basis of this available session, you can use these attack modules. I don't see a session available on your screenshot. You can refer to the tutorial here: https://www.yuque.com/viper-en/inh85g/gyvkrq

**Comment by FunnyWolf** [comment]
> **描述Bug** I am very new to using this awesome framework tool.
> 
> I read the modules' readme under (https://www.yuque.com/vipersec/module/taxm8t) and I found some of the modules are missing, e.g. Office宏钓鱼文档
> 
> ![image](https://user-images.githubusercontent.com/29709246/143687027-e7638efb-cbcc-4454-91b6-8412b99e5831.png)
> 
> Is this a bug or intentionally hiding? Thanks.
> 
> **如何复现**
> 
> 1. Install viper by using F8X script
> 2. There is no module under "Automation -> Initial Access"
> 
> ![image](https://user-images.githubusercontent.com/29709246/143687100-6de111ca-4926-4eb5-a54b-a5e1ff9155f3.png)
> 
> Thanks.
> 
> **截图** Provided in the above description. Thanks.
> 
> @FunnyWolf

Hi,I need more infomation to check where the problem is,would you feedback logs in `uwsgi.log` and `viperpython.log`,
You can download logs files it in the location described in the picture below
![image](https://user-images.githubusercontent.com/17685281/143729985-c210bf82-02cc-42d4-9335-cba3742a0279.png)
