### ISSUE TITLE
[BUG]session无法加载

### ISSUE THREAD

**Issue by famei** [FunnyWolf/Viper#76]
**描述Bug**
mfs内有session 但前端无法立即显示  必须等待1至3分钟后才能显示  

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 设置windows/meterpreter/reverse_winhttps监听
3. 设置监听防火墙 打开屏蔽沙箱IP 
4. Bug出现了

**版本**
v1.5.9 20211204
Ubuntu 20.04.1 LTS
Google Chrome  96.0.4664.45

**截图**
![1](https://user-images.githubusercontent.com/61237921/144730852-da379e93-842a-48c4-a52f-ef54a3f86342.png)
![2](https://user-images.githubusercontent.com/61237921/144730856-f56449cc-b5b7-4011-b718-3b8d3b5c01d4.png)
![3](https://user-images.githubusercontent.com/61237921/144730860-587ebad5-33b1-4551-b018-5d680ca45bfd.png)

日志 
[logs-1638670557.zip](https://github.com/FunnyWolf/Viper/files/7655081/logs-1638670557.zip)
@Funnywolf

**Comment by FunnyWolf** [comment]
未完成初始化的session会显示在255.255.255.255这个主机下面
![image](https://user-images.githubusercontent.com/17685281/144731891-bdf7afdf-20c6-4ecb-8f3b-0031ab73da9f.png)

问题出在为什么没有自动生成255.255.255.255这个主机
另外session上线慢是因为ssl加密协商问题.
```[12/05/2021 02:01:09] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 16>```

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/viperpython/commit/adec10e1ac0e52b203b7f4d88c1eebfefa371f77
