### ISSUE TITLE
[BUG] 重启之后渗透服务不可用

### ISSUE THREAD

**Issue by xiyan123** [FunnyWolf/Viper#77]
**描述Bug**
请简短描述遇到的Bug.

重启之后渗透服务连接失败,请检查MSFRPC状态

WARNING: Local file /root/metasploit-framework/data/mettle/i486-linux-musl/bin/mettle is being used
WARNING: Local files may be incompatible Metasploit framework
WARNING: Local file /root/metasploit-framework/data/mettle/x86_64-linux-musl/bin/mettle is being used
WARNING: Local file /root/metasploit-framework/data/meterpreter/metsrv.x64.dll is being used
WARNING: Local files may be incompatible with the Metasploit Framework

**截图**
请提供Bug出现时的截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug** 请简短描述遇到的Bug.
> 
> 重启之后渗透服务连接失败,请检查MSFRPC状态
> 
> WARNING: Local file /root/metasploit-framework/data/mettle/i486-linux-musl/bin/mettle is being used WARNING: Local files may be incompatible Metasploit framework WARNING: Local file /root/metasploit-framework/data/mettle/x86_64-linux-musl/bin/mettle is being used WARNING: Local file /root/metasploit-framework/data/meterpreter/metsrv.x64.dll is being used WARNING: Local files may be incompatible with the Metasploit Framework
> 
> **截图** 请提供Bug出现时的截图.
> 
> @FunnyWolf

重启之后等一会(30秒)服务才能起来
