### ISSUE TITLE
[BUG]-同一台主机，不同的地址回连，前端生成多个主机

### ISSUE THREAD

**Issue by AdminPoker** [FunnyWolf/Viper#78]
在同一台主机上安装了elf shell，在前端生成了好几个主机项
<img width="1785" alt="图片" src="https://user-images.githubusercontent.com/51812136/146168959-d17d61ed-5533-4517-836a-d849add22934.png">
推荐解决方案
获取到主机后，后端先使用主机名+主机ip地址+主机若干配置信息生成md5值，然后前端进行解析的时候，在碰到不同的主机回连，先获取主机信息加密的hash，再hash比对，如果hash和已有的一致，就前端显示的时候并入到现有的主机项里面去

**Comment by FunnyWolf** [comment]
> 在同一台主机上安装了elf shell，在前端生成了好几个主机项 <img alt="图片" width="1785" src="https://user-images.githubusercontent.com/51812136/146168959-d17d61ed-5533-4517-836a-d849add22934.png"> 推荐解决方案 获取到主机后，后端先使用主机名+主机ip地址+主机若干配置信息生成md5值，然后前端进行解析的时候，在碰到不同的主机回连，先获取主机信息加密的hash，再hash比对，如果hash和已有的一致，就前端显示的时候并入到现有的主机项里面去

这个主机是有多个网卡吗?172和10.244是两个网卡地址?
