### ISSUE TITLE
[BUG]扫描log4j漏洞dnslog没有收到记录

### ISSUE THREAD

**Issue by thereallry** [FunnyWolf/Viper#80]
**描述Bug**
通过手动测试保证了dnslog和目标网站没有问题，符合触发log4j漏洞的条件。尝试使用viper进行扫描，配置了dnslog域名，访问相同的目标网站，dnslog没有收到记录。

**如何复现**
1. 启动viper
2. 配置DNSLOG域名
3. 配置并启动浏览器代理
4. 访问目标网站

ps: 如何看到替换payload重新发送请求的日志来进行排查？

@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug** 通过手动测试保证了dnslog和目标网站没有问题，符合触发log4j漏洞的条件。尝试使用viper进行扫描，配置了dnslog域名，访问相同的目标网站，dnslog没有收到记录。
> 
> **如何复现**
> 
> 1. 启动viper
> 2. 配置DNSLOG域名
> 3. 配置并启动浏览器代理
> 4. 访问目标网站
> 
> ps: 如何看到替换payload重新发送请求的日志来进行排查？
> 
> @FunnyWolf

viper 2021-12-20 更新了新版本,请参考最新教程
https://www.yuque.com/vipersec/blog/lgrqm4#TeWHQ
