### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhengjiashengbaba** [FunnyWolf/Viper#81]
这边运行 docker-compose up -d 却没在本地看到镜像 和容器运行，是怎么回事呢

![image](https://user-images.githubusercontent.com/54987693/148484368-0f8e756a-3a04-48dc-8f46-6b36541f3b2d.png)

**Comment by zhengjiashengbaba** [comment]
麻烦各位大佬解答

**Comment by FunnyWolf** [comment]
> 这边运行 docker-compose up -d 却没在本地看到镜像 和容器运行，是怎么回事呢
> 
> ![image](https://user-images.githubusercontent.com/54987693/148484368-0f8e756a-3a04-48dc-8f46-6b36541f3b2d.png)

硬盘空间不够了,删除几个images就可以了
