### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 19770214** [FunnyWolf/Viper#84]
**描述Bug**
无法正常迁移进程,不断提示缺少参数

**如何复现**
请说明如何复现Bug:
1. Session上线
2. 直接迁移，报错

**截图**
请提供Bug出现时的截图.
暂时没有机子，等到过段时间买了新的机子装了之后给截屏（

PS:这个是MSF的问题，我看MSF框架的GitHub Issue有人反馈，官方已经修复，但是由于Viper面板的MSF不是最新的，所以未应用修复导致的此问题
@Funnywolf

**Comment by FunnyWolf** [comment]
> **描述Bug** 无法正常迁移进程,不断提示缺少参数
> 
> **如何复现** 请说明如何复现Bug:
> 
> 1. Session上线
> 2. 直接迁移，报错
> 
> **截图** 请提供Bug出现时的截图. 暂时没有机子，等到过段时间买了新的机子装了之后给截屏（
> 
> PS:这个是MSF的问题，我看MSF框架的GitHub Issue有人反馈，官方已经修复，但是由于Viper面板的MSF不是最新的，所以未应用修复导致的此问题 @FunnyWolf

有msf官方issus的地址吗?

**Comment by 19770214** [comment]
https://github.com/rapid7/metasploit-framework/issues/12993

**Comment by FunnyWolf** [comment]
已经修了,下个版本合并

**Comment by 19770214** [comment]
ok
