### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CHNmyx** [FunnyWolf/Viper#86]
登录的时候显示502错误

1. 安装Viper
2. 打开浏览器
3. 输入密码
4. 点击确定
5. Bug出现了

@Funnywolf

**Comment by FunnyWolf** [comment]
> 登录的时候显示502错误
> 
> 1. 安装Viper
> 2. 打开浏览器
> 3. 输入密码
> 4. 点击确定
> 5. Bug出现了
> 
> @FunnyWolf

后台没起来,等一会就好了

**Comment by CHNmyx** [comment]
额 我换了个浏览器就可以了，但是火狐还是上不去    感谢大佬
