### ISSUE TITLE
[BUG]安装在vps上，会莫名超时

### ISSUE THREAD

**Issue by wxx0105** [FunnyWolf/Viper#89]
监听器啥的一瞬间都消失了
![image](https://user-images.githubusercontent.com/71886755/164604518-3244c0c0-a1f9-42c0-89cb-d5bbe57d6c9b.png)
然后就显示这张图，也出现msf异常，跪求作者大大看看。

**Comment by FunnyWolf** [comment]
能自动恢复不？

**Comment by wxx0105** [comment]
很遗憾不能，重新装了一次又不行了，求解决

**Comment by wxx0105** [comment]
系统是腾讯云centos8,2，2h2g，使用手动安装

**Comment by wxx0105** [comment]
系统设置了常驻cs4.0服务器，不懂这个有没有影响

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/issues/62 是不是也用了内网代理和端口转发功能?

**Comment by wxx0105** [comment]
我是手动安装的，那时候我是按照文档打上去的。
tee docker-compose.yml <<-'EOF'
version: "3"
services:
  viper:
    image: registry.cn-shenzhen.aliyuncs.com/toys/viper:latest
    container_name: viper-c
    network_mode: "host"
    restart: always
    volumes:
      - ${PWD}/loot:/root/.msf4/loot
      - ${PWD}/db:/root/viper/Docker/db
      - ${PWD}/module:/root/viper/Docker/module
      - ${PWD}/log:/root/viper/Docker/log
      - ${PWD}/nginxconfig:/root/viper/Docker/nginxconfig
    command: ["VIPER_PASSWORD"]
EOF
不懂是不是这一段是不是我要自己设置什么？

**Comment by wxx0105** [comment]
这个会不会与cs服务器的开启有关，我之前安装好之后就上线cs的服务器了，这次重装后我不上cs服务器试试看。

**Comment by wxx0105** [comment]
是我自己的vps开放端口过多吗？其实我全开了端口，我现在关闭一些端口试试，因为vps还安装了vulfocus。感谢回复

**Comment by FunnyWolf** [comment]
> > > 这个会不会与cs服务器的开启有关，我之前安装好之后就上线cs的服务器了，这次重装后我不上cs服务器试试看。
> > 
> > 
> > 这个和CS应该不冲突,还是msf服务问题,这个问题之前都是由于开放端口连接过多导致的
> 
> ~什么时候支持CS联动~

已经支持，有模块

**Comment by wxx0105** [comment]
感谢回复，我马上重新上线viper，hw到来，希望可以有所成绩，感谢
