### ISSUE TITLE
Console页面输入数据无法使用左右键盘移动光标

### ISSUE THREAD

**Issue by ViCrack** [FunnyWolf/Viper#9]
![图片](https://user-images.githubusercontent.com/18179821/108589159-10434780-7398-11eb-81b6-0c733af5dd75.png)

![图片](https://user-images.githubusercontent.com/18179821/108589182-2bae5280-7398-11eb-8c8b-70841cb0eb9d.png)

界面对一些按键支持还不是很好, 比如无法使用左右键盘移动光标, 按了HOME键之后就会导致屏幕错乱
万一输入错的话还是有点麻烦

![图片](https://user-images.githubusercontent.com/18179821/108589045-68c61500-7397-11eb-95c3-4d82a40f830b.png)

另外这里能不能加一个server酱的通知

**Comment by FunnyWolf** [comment]
Console处理左右键和home键需要对输出缓存进行操作,处理起来非常麻烦,又不愿意写,所以偷懒前端直接屏蔽了左右键(home键忘屏蔽了)

**Comment by FunnyWolf** [comment]
[server酱 commit](https://github.com/FunnyWolf/Viper/commit/60d1d1220ac91eaa09bdefda6c2753dce6d743a3)

**Comment by ViCrack** [comment]
![图片](https://user-images.githubusercontent.com/18179821/108630233-bbd6bf80-749e-11eb-9b10-cae6d488b7f6.png)
server酱的试了已经可以用了
