### ISSUE TITLE
[BUG] Not Found: /ws/v1/websocket/heartbeat/

### ISSUE THREAD

**Issue by DNLINYJ** [FunnyWolf/Viper#91]
**描述Bug**
打开VIPER一直加载 渗透服务正常 LOG显示Not Found: /ws/v1/websocket/heartbeat/
[日志文件](https://github.com/FunnyWolf/Viper/files/8646688/logs-1651999799.zip)

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 输入密码
4. Bug出现了

**截图**
![image](https://user-images.githubusercontent.com/82745795/167289323-06b78898-0381-4847-a493-c41f25ede2d5.png)

@Funnywolf

**Comment by DNLINYJ** [comment]
同时还有ruby突然CPU占用高并一直保持的问题 导致VIPER无法使用

**Comment by FunnyWolf** [comment]
汇总到以下issus,关闭此issus
https://github.com/FunnyWolf/Viper/issues/129
