### ISSUE TITLE
[BUG]渗透服务连接失败,请检查MSFRPC状态

### ISSUE THREAD

**Issue by itry02** [FunnyWolf/Viper#94]
在实际渗透中 靶机centos6.6 无waf 阿里云 攻击机Ubuntu 18.04 主机上线我就开始访问各种目录 访问了十几个目录就报这个错误 没有操作其他的 这个是什么问题 不清楚是被杀还是什么？

06-02 04:30:55模块: 主机基础信息 SID: 1 开始执行
06-01 18:05:46渗透服务连接失败,请检查MSFRPC状态
06-01 18:04:33渗透服务连接失败,请检查MSFRPC状态
06-01 18:03:51渗透服务连接失败,请检查MSFRPC状态
06-01 17:58:33MSFRPC> Invalid method parameter(s).
06-01 17:20:13MSFRPC> Invalid method parameter(s).
06-01 17:20:05MSFRPC> Invalid method parameter(s).
06-01 17:14:59MSF >> Get PINFO : execution expired
06-01 17:14:32MSF >> Get PINFO : execution expired

**Comment by FunnyWolf** [comment]
https://github.com/FunnyWolf/Viper/commit/16a24a52e0fabaaff410d1a2f5d22e991ea3a37f

**Comment by Aliak15** [comment]
我运行了一条命令解决了
docker-compose start
