### ISSUE TITLE
关于压缩回传模块的建议①不能压缩带有空格的目录；②压缩时会在靶机桌面生成一个viper的exe文件去压缩目录，图标明显；③靶机文件夹压缩完毕之后默认存放位置是桌面，太明显

### ISSUE THREAD

**Issue by qwc158** [FunnyWolf/Viper#95]
**描述Bug**
请简短描述遇到的Bug.

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 输入密码
4. Bug出现了

**截图**
请提供Bug出现时的截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
文件的目录默认使用session loader所在的目录
